### ISSUE TITLE
New credit feature to BR is terminating the script

### ISSUE THREAD

**Issue by ssgdodd** [sealemar/BingRewards#105]
A new feature added to Bing Rewards is now terminating the script.  Output is as follows:

Traceback (most recent call last):
  File "C:\br-master\main.py", line 293, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "C:\br-master\main.py", line 291, in <module>
    __run(config)
  File "C:\br-master\main.py", line 217, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "C:\br-master\main.py", line 204, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "C:\br-master\main.py", line 177, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "C:\br-master\main.py", line 54, in earnRewards
    rewards = bfp.parseFlyoutPage(bingRewards.requestFlyoutPage(), bingCommon.BING_URL)
  File "C:\br-master\pkg\bingFlyoutParser.py", line 103, in parseFlyoutPage
    parser.feed(page[s:e])
  File "C:\Python27\lib\HTMLParser.py", line 114, in feed
    self.goahead(0)
  File "C:\Python27\lib\HTMLParser.py", line 152, in goahead
    if i < j: self.handle_data(rawdata[i:j])
  File "C:\br-master\pkg\bingFlyoutParser.py", line 233, in handle_data
    self.reward.progressMax = int(progress[1])
ValueError: invalid literal for int() with base 10: '1 credit'

**Comment by ssgdodd** [comment]
It may be the "Earn and explore" feature added yesterday.

**Comment by ssgdodd** [comment]
Correction - the issue is not a new feature, but rather a restructured representation of the credit data on the dashboard.  Before, (I assume) it was a simple numeric, but now the code is parsing the area it did before and is finding a alphanumeric string, which is failing because it its expecting a numeric value.

**Comment by amayer5125** [comment]
I believe this is being worked on in #104

**Comment by chuy124** [comment]
Is there a workaround?

**Comment by amayer5125** [comment]
@chuy124 #104 works for me. You just need to update line 234 of pkg/bingFlyoutParser.py with `self.reward.progressMax = int(progress[1].split()[0])`

**Comment by chuy124** [comment]
Thanks Alex, just tried it and it works for me too.

**Comment by ssgdodd** [comment]
Yep - that was it.  I was barking up the same tree, but since my primary language is SQL, it was taking me a bit longer. Thanks!

**Comment by itssasanka** [comment]
FYI I already fixed it in #104

**Comment by amayer5125** [comment]
@itssasanka I had mentioned it higher in the comments. Im sure after @sealemar gets a chance he will check it out and merge it.

**Comment by Dmurph24** [comment]
Also fixed the problem I was having! Thanks!

**Comment by sealemar** [comment]
fixed in #104 . thank you all
