### ISSUE TITLE
int parse failure in getRewardsPoints

### ISSUE THREAD

**Issue by jamre** [sealemar/BingRewards#112]
my report activity page is returning "Rewards" instead of the number of accumulated points this morning. Is anyone else having this problem?

page:
```
c=sj_cook.set;var t=_ge('id_rc');if(o=_ge('id_r')){o.style.display='block';}if(t)t.innerHTML='Rewards';c('_SS','R','-1',0,'/');c('_RwBf','s','100',1,'/');c('_RwBf','o','2',1,'/');sj_evt.bind("bepready",function(args){args[1]('0');},1);
```

Traceback (most recent call last):
```
  File "./main.py", line 306, in <module>
    __run(config)
  File "./main.py", line 231, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "./main.py", line 205, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "./main.py", line 178, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "./main.py", line 54, in earnRewards
    reportItem.oldPoints = bingRewards.getRewardsPoints()
  File "./pkg/bingRewards.py", line 165, in getRewardsPoints
    return int(p)
ValueError: invalid literal for int() with base 10: 'Rewards'
```

**Comment by Dmurph24** [comment]
Double check that your accounts are not banned. I thought I had the same issue but turned out every one of my account got banned this morning

**Comment by chipmanly** [comment]
All of my accounts were banned as well.  

My setup:
I run this script on 5 different PCs, each with unique static IP addresses and 4 or less bing accounts per instance.  Three configs use the Bing generator and two use the Wikipedia generator.  Up until today I have had minimal bans.  I typically go a week or more between redemptions per IP address.

I have one unscripted account that I search from daily. It uses the same IP as two of the instances (home & work).  It has not been banned.

**Comment by Dmurph24** [comment]
Im with you, I was not banned very much either. They must have done a huge
ban across everyone today. It would be interesting to see what they look at
to determine if you get banned.

**Comment by amayer5125** [comment]
I only run 2 accounts. One main account and one for dev/testing.
neither has been banned.
@chipmanly @Dmurph24 do you run your scripts at random times or at the same time every day (ie. cron job)?

**Comment by Dmurph24** [comment]
I run mine at random times

**Comment by chipmanly** [comment]
I had trouble implementing randomness via the cron job, so my crontab looks something like:

22    11   *   *   0   [redacted]
31    15   *   *   1   [redacted]
44    13   *   *   2   [redacted]
12    12   *   *   3   [redacted]
35    14   *   *   4   [redacted]
21    16   *   *   5   [redacted]
43    10   *   *   6   [redacted]

**Comment by PlasmaPower** [comment]
I have mine running every 3 hours or something like that (it's not random) with one account and I didn't get banned.

**Comment by chipmanly** [comment]
The top post in r/beermoney suggests this is widespread and not exclusive to this script.

**Comment by PlasmaPower** [comment]
It would seem having too many accounts is not a good idea.

**Comment by sealemar** [comment]
@jamre and others - are any of you guys still having the issue?

**Comment by twillowman** [comment]
I use the script with Wikipedia searches for 3 accounts at a random time per day. Never had any banning issues.

**Comment by jamre** [comment]
Yeah, they banned me :-(
I had two accounts running in this script and one that I did manually. Only the scripted ones got banned.
