### ISSUE TITLE
Don't fail the script, but warn the user if an account is banned

### ISSUE THREAD

**Issue by iceberg1369** [sealemar/BingRewards#114]
I got following error 
Traceback (most recent call last):
  File "main.py", line 295, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "main.py", line 293, in <module>
    __run(config)
  File "main.py", line 218, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGEN
TS_PC, doSleep)
  File "main.py", line 205, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "main.py", line 178, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "main.py", line 53, in earnRewards
    reportItem.oldPoints = bingRewards.getRewardsPoints()
  File "pkg\bingRewards.py", line 167, in getRewardsPoints
    return int(page[s:e])
ValueError: invalid literal for int() with base 10: 'Rewards'

I use windows

**Comment by PlasmaPower** [comment]
I think that happens when you get a temporary ban. Try running it again in a little bit.

**Comment by iceberg1369** [comment]
these error throws when account disqualified from the program, so it should be considered to eleminated in the loop

**Comment by PlasmaPower** [comment]
I don't get what you mean. Are you talking about error handling?

**Comment by iceberg1369** [comment]
some accounts get banned from bingrewards program, so script should ignore those accounts rather than throwing an exception and continue with next account. currently script stops completely in this case

**Comment by sealemar** [comment]
@iceberg1369 I tend to agree with you on the matters of the reason, but I'm absolutely not sure whether you can make assumptions on that script is misfunctioning or the account is banned based on that exception. A better way to understand a ban would be to have an extra check in ```except``` section or before the ```int``` parsing. That check should confirm that the page which was received from Bing! doesn't look like a ban page.

**Comment by iceberg1369** [comment]
thanks for your response, but unfortunately I don't have python skill to edit the script

**Comment by sealemar** [comment]
Ok, I'm changing the subject line of this issue. Since the original issue is resolved and we agreed that the account was banned, this issue becomes a task to come up with a piece of logic to account for that kind of the script failure and to warn the user, rather than fail the entire script.

**Comment by iceberg1369** [comment]
I can give you a banned account to investigate it and parse it

**Comment by sealemar** [comment]
I don't think I have time for that. This issue is looking for volunteers.
