### ISSUE TITLE
Crontab sleep function not working?

### ISSUE THREAD

**Issue by Dmurph24** [sealemar/BingRewards#117]
Maybe this is just me, but I have set up the program in crontab to sleep randomly before each run and each execution has never been random. I even use the full paths to the functions to make the program sleep. Additionally, I went outside of your tutorial and looked for a different syntax to make the program sleep in crontab and used
<code>8 0 * * * /bin/sleep '/usr/bin/expr $RANDOM \% 7200';  </code>
This did not error, but also did not sleep...However, whats strange is that this will work in terminal if you pull out the escape before the percentage. Just wanted to know if anyone else had an issue with this. If no one has, this issue may be closed.

**Comment by PlasmaPower** [comment]
What is the result of `which sleep` in your terminal?

**Comment by Dmurph24** [comment]
/bin/sleep, and yes I know, but it was in the guide for the program

**Comment by PlasmaPower** [comment]
The only thing I can think of is simply having your terminal run it:
```
 8 0 * * * /bin/bash -c "sleep '/usr/bin/expr $RANDOM \% 7200'"; 
```
If you use a terminal other than bash, replace it with that.

**Comment by Dmurph24** [comment]
Alright I'll try that after work. Thanks for the suggestion!

**Comment by sealemar** [comment]
did you put everything from [the man](http://sealemar.blogspot.com/2013/10/bing-rewards-automation-script-unix-cron.html) to your crontab?

```
PATH=/usr/bin:$PATH
LOCAL_CONFIG_DIR=/home/bingrewards/etc

0   1   *   *   *   sleep $(($RANDOM \% 120))m && python2 /home/bingrewards/bin/main.py 2>&1 | gzip > /home/bingrewards/var/log/bingrewards/`date "+\%Y-\%m-\%dT\%H:\%M:\%S"`.log.gz
```

**Comment by PlasmaPower** [comment]
Yeah, I was thinking that command wouldn't work. It doesn't on my system.

**Comment by Dmurph24** [comment]
I used that exact command and it still runs but not randomly.

**Comment by sealemar** [comment]
put this line to the beginning of your crontab:

```
SHELL=/bin/bash
```

**Comment by Dmurph24** [comment]
Thank you, this solution worked for me and the program is now sleeping randomly. Any idea why this was happening?

**Comment by sealemar** [comment]
That was happening because ```cron``` picks a default shell if you don't set it explicitly. A default shell on is different on different flavors of the OS. I personally prefer ```bash```. Also it's almost a golden standard I would say. That means whenever you want a shell script to work you want to put

```#!/bin/bash```

at the top, or 

```SHELL=/bin/bash```

in case of cron

**Comment by kushannshah** [comment]
SHELL=/bin/bash

Worked for me.
thanks.
Kushan
