### ISSUE TITLE
ignore temporary blocked accounts and dont fail, just like banned accounts

### ISSUE THREAD

**Issue by iceberg1369** [sealemar/BingRewards#118]
script fails when a account is temporary blocked. these accounts need phone verifications and etc. so script should be able to ignore that accounts and jump to the  next one. as I noticed so far, the script ignores banned accounts but not temporary blocked ones.

**Comment by PlasmaPower** [comment]
What is the crash log?

**Comment by iceberg1369** [comment]
I will try to paste ASAP I face crash

**Comment by iceberg1369** [comment]
Live - logan.white****@outlook.com
Result 1/3:
-----------
name        : Search and earn
url         : http://www.bing.com/explore/rewards?FORM=MI0GML&PUBL=MUIDTrial&CR
A=MI0GML
progressCur : 0
progressMax : 10
progress %  : 0.00%
description : For a limited time you're earning free credits. Activate your acc
unt to claim them.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 2/3:
-----------
name        : What are the rewards?
url         : http://www.bing.com/explore/rewards?FORM=MI0GN4&PUBL=MUIDTrial&CR
A=Cell2Y&programName=Cell2
description : Get gift cards from places like Amazon.com and Fandango, or suppo
t your favorite charity.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 3/3:
-----------
name        : Join Bing Rewards. It's free!
url         : http://www.bing.com/explore/rewards?FORM=MI0GN4&PUBL=MUIDTrial&CR
A=Cell2Y&programName=Cell2
description : Use Bing. Join Bing Rewards to start earning credits toward free
ewards.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn


For: Live - logan.white****@outlook.com

--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 299, in <modul
e>
    EventsProcessor.onScriptFailure(config, e)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 297, in <modul
e>
    __run(config)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 222, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGEN
TS_PC, doSleep)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 209, in __proc
essAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 182, in __proc
essAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "C:\Users\Administrator\Desktop\BingRewards\main.py", line 69, in earnRew
ards
    reportItem.lifetimeCredits = bingRewards.getLifetimeCredits()
  File "C:\Users\Administrator\Desktop\BingRewards\pkg\bingRewards.py", line 140
, in getLifetimeCredits
    s = page.index('<div class="data-lifetime')
ValueError: substring not found

C:\Users\Administrator\Desktop\BingRewards>

**Comment by iceberg1369** [comment]
here is the html source for blocked page when you try to login
http://pastebin.com/uNWMhDgZ

**Comment by goostoff** [comment]
Take a look at #120 and #114.  #114 is already in the code base and #120 is ready for pull.  These may resolve the issue you are seeing.

**Comment by iceberg1369** [comment]
they just ignore banned accounts not temporary blocked ones

**Comment by sealemar** [comment]
Does that https://github.com/sealemar/BingRewards/pull/120 fix the issue?

**Comment by goostoff** [comment]
From the testing on my active/banned accounts: 
"Could not get the number of rewards: Account banned (at least temporarily)" - Banned from BingRewards
"User was not successfully signed in (possibly banned)" - Temporary ban from Microsoft sites

Both of these are ignored and the script will not terminate.

**Comment by sealemar** [comment]
@iceberg1369 do you want to confirm and close the issue?

**Comment by iceberg1369** [comment]
here is the output of an account which needs phone verification to get unblocked
good thing is that script doesn't crash anymore, but it still prints out some junk information.
but I think it would be good if script do some clean up.


2015-02-19 10:35:22.9 - script started
--------------------------------------------------------------------------------


Protocols: 'http, https', Proxy: '127.0.0.1:8580'
Live - brianna.stewart****@outlook.com
Result 1/3:
-----------
name        : Search and earn
url         : http://www.bing.com/explore/rewards?FORM=MI0GML&PUBL=MUIDTrial&CRE
A=MI0GML
progressCur : 0
progressMax : 10
progress %  : 0.00%
description : For a limited time you're earning free credits. Activate your acco
unt to claim them.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 2/3:
-----------
name        : What are the rewards?
url         : http://www.bing.com/explore/rewards?FORM=MI0GN4&PUBL=MUIDTrial&CRE
A=Cell2Y&programName=Cell2
description : Get gift cards from places like Amazon.com and Fandango, or suppor
t your favorite charity.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 3/3:
-----------
name        : Join Bing Rewards. It's free!
url         : http://www.bing.com/explore/rewards?FORM=MI0GN4&PUBL=MUIDTrial&CRE
A=Cell2Y&programName=Cell2
description : Use Bing. Join Bing Rewards to start earning credits toward free r
ewards.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

BingAccountError: User was not successfully signed in (possibly banned)


For: Live - brianna.stewart****@outlook.com

--------------------------------------------------------------------------------

Total points earned: 0

2015-02-19 10:35:33.8 - script ended

**Comment by sealemar** [comment]
The information which the script prints out is standard. The output doesn't prevent the script from skipping banned accounts. It's the user responsibility to detect an account failure. As one of the contributor said: _the script is only as smart as we make it_. I'm closing the issue.
