### ISSUE TITLE
"Freebie" points not working

### ISSUE THREAD

**Issue by bbenz3** [sealemar/BingRewards#124]
I'm not sure if it is just me or not but for some reason none of my accounts will get the "freebie" point each day. I check and have to manually select them which isn't a huge deal but it would be nice if it would capture this point.

Is anyone else having this issue?

**Comment by PlasmaPower** [comment]
Mine seem to be earning, except the trivia tuesday ones which I don't think can be easily automated.

**Comment by bbenz3** [comment]
Hmm... not sure what I am doing wrong then.

**Comment by amayer5125** [comment]
I get all my freebie points too. @bbenz3 are you using the most recent version of the script?

**Comment by bbenz3** [comment]
Yes I updated before I commented too make sure that wasn't my problem. I have five accounts and sometimes the accounts don't capture ask if the other points as well, but one common thing is that none of them capture the freebie.

**Comment by sealemar** [comment]
@bbenz3 can you post the logs?

**Comment by bbenz3** [comment]
Well I re-downloaded the latest version and I get the freebie points now... but I don't have a proxy account so I left it blank and now the script fails. I commented out that part of the python script so it works but am I doing something wrong?

**Comment by sealemar** [comment]
It's hard to tell until you post your ```config.xml``` and the exception with the stack trace.

**Comment by amayer5125** [comment]
@bbenz3 you should just be able to let the proxy part commented out in the config without a problem.
Is the script working for you now?
