### ISSUE TITLE
Parse Errors?

### ISSUE THREAD

**Issue by samesjong** [sealemar/BingRewards#127]
I just installed Python 2.7.9 on OS X and just installed the BingRewards zip. I've checked the config.xml file and everything looks good (just using one account so pretty simple), and I went through the troubleshooter after receiving the message below. When I comment out the events section I still receive the same message below. Please help.

Thank you!

Traceback (most recent call last):
  File "/Users/James/Desktop/BingRewards-master/main.py", line 289, in <module>
    config.parseFromFile(configFile)
  File "/Users/James/Desktop/BingRewards-master/pkg/config.py", line 507, in parseFromFile
    tree = et.parse(configFile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 27, column 22

**Comment by sealemar** [comment]
that's not very informative. Can you paste your ```config.xml``` with ellipsis instead of your account name/password?

**Comment by samesjong** [comment]
<?xml version="1.0"?>

<configuration>
    <general
        betweenQueriesInterval="15.0"
        betweenQueriesSalt="12.0"
        betweenAccountsInterval="300"
        betweenAccountsSalt="600"
        addSearchesDesktop="0"
        addSearchesDesktopSalt="20"
        addSearchesMobile="0"
        addSearchesMobileSalt="20" />
    

    

    <accounts>
        <account type=“Live” disabled="false">
            <login>…</login>
            <password>…</password>
        </account>
        <account type="Facebook" disabled="true">
            <login>blabla@mail.com</login>
            <password>xxx</password>
        </account>
        <account type="Live" disabled=“true”>
            <login>gogo@hotmail.com</login>
            <password>xxx</password>
        </account>
        <account type="Live" disabled=“true”>
            <login>hoho@hotmail.com</login>
            <password>xxx</password>
        </account>
    </accounts>

<!—-
    <events>
        <onError>
            <retry interval="15" salt="13.5" count="3" />
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onError.sh %a %p %r %P %l %i %e" />
        </onError>
        <onComplete>
            <retry if="%p lt 16" interval="15" salt="13.5" count="3" />
            <notify if="%l gt 3000"
                    cmd='/home/BingRewards/bin/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
            <notify if="%p ne 16"
                    cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            <notify if="%P gt 475"
                    cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />

            <account ref="Live_gogo@hotmail.com">
                <retry if="%p lt 16" interval="15" salt="13.5" count="3" />
                <notify if="%l gt 750"
                        cmd='/home/BingRewards/bin/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "Gold with %l Life Credits"' />
                <notify if="%p ne 16"
                        cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                <notify if="%P gt 475"
                        cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            </account>
            <account ref="Facebook_john.smith@gmail.com">
                <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                <notify if="%l gt 10000"
                        cmd='/home/BingRewards/bin/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                <notify if="%p ne 31"
                        cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                <notify if="%P gt 475"
                        cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            </account>
        </onComplete>
        <onScriptComplete>
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onScriptComplete.sh -mail" />
        </onScriptComplete>
        <onScriptFailure>
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onScriptFailure.sh -mail" />
        </onScriptFailure>
    </events>
—->
    
    <queries generator="wikipedia" />
</configuration>

I didn't touch anything but the account name/password portion

**Comment by sealemar** [comment]
Please, use markdown to get your text nicely formatted.
_Note: I've changed your post_

**Comment by samesjong** [comment]
Sorry about that. Very new to this all. Is there anything I messed up in the xml file?

**Comment by sealemar** [comment]
if that is exactly your config.xml it won't work because the accounts are not set up. If that's not your config.xml, that doesn't give any extra information and please post your config.

**Comment by amayer5125** [comment]
@samesjong you need to comment out the accounts you arent using

**Comment by amayer5125** [comment]
Nevermind... Just saw they were disabled :p

**Comment by samesjong** [comment]
When you say the accounts are not set up, I just have one account and I replaced the user/password with ellipses as you had stated. Haha you got me excited @amayer5125

**Comment by amayer5125** [comment]
Either way it cant hurt to delete them or comment them out.
also I would keep the main `<events>` tag uncommented and just comment out the guts of that tag.

**Comment by sealemar** [comment]
```
ParseError: not well-formed (invalid token): line 27, column 22
```

that means your ```config.xml``` is malformed at that position which is the third character of your account login.

**Comment by samesjong** [comment]
I have confirmed the account information and it was inserted in the same format as the examples.

**Comment by amayer5125** [comment]
@samesjong do you have any weird characters in your email or password? examlple quotes (") or less/greater than (<>)

**Comment by samesjong** [comment]
Nope, nothing weird at all just letters.

**Comment by amayer5125** [comment]
try this config and just put your username and passwork in the correct spots. I just removed all the comments and simplified it.
```xml
<?xml version="1.0"?>
<configuration>
    <general
        betweenQueriesInterval="15.0"
        betweenQueriesSalt="12.0"
        betweenAccountsInterval="300"
        betweenAccountsSalt="600"
        addSearchesDesktop="5"
        addSearchesDesktopSalt="15"
        addSearchesMobile="5"
        addSearchesMobileSalt="10" />
    <accounts>
        <account type="Live" disabled="false">
            <login></login>
            <password></password>
        </account>
    </accounts>
    <events>
    </events>
    <queries generator="wikipedia" />
</configuration>
```

**Comment by sealemar** [comment]
@samesjong I've found the issue, but I will let you identify it yourself. Here is the tool I've used
http://www.w3schools.com/xml/xml_validator.asp

You just copy-paste your config xml there and click validate

**Comment by amayer5125** [comment]
Did you edit this in Word or something? Or are macs just weird?

**Comment by sealemar** [comment]
macs aren't weird, I'm a mac user

**Comment by samesjong** [comment]
@amayer5125 
That worked for me. I edited in textedit, Macs are great

@sealemar I tried that and it said it was expecting quotations (i'm assuming around my username), but that did not fix the problem.

**Comment by sealemar** [comment]
@samesjong did you understand the validation error the tool showed you?

**Comment by amayer5125** [comment]
@samesjong Your quotes were not ascii quotes they were unicode quotes. Also you had mdash instead of two dashes.

**Comment by samesjong** [comment]
“ vs "
Got it. Thank you guys so much! I guess textedit was automatically changing them.

**Comment by amayer5125** [comment]
Glad we could get it working :)
