### ISSUE TITLE
Feature Request: Ability to automatically reedem when phone is set

### ISSUE THREAD

**Issue by Dmurph24** [sealemar/BingRewards#129]
I know this might be a long shot, but if the script automatically redeemed the points that it earned would be prettyy awesome. Im am aware that this cannot be done if a phone is not already set for the account, but if it is we should start looking into this. Thoughts?

**Comment by PlasmaPower** [comment]
Are you talking about phone searches? The script automatically does those.

**Comment by Dmurph24** [comment]
No. I am talking about redeeming gift cards.

**Comment by amayer5125** [comment]
@Dmurph24 I believe sometimes bing asks you to enter a captcha. This would make redeeming rewards very tricky.
Also I dont think redeeming rewards right when you have enough points is a very human like behavior. Personally I redeem 3 or 4 at a time. If you always redeemed points when you had just enough credits I think this would throw up some flags to bing. I could be in the minority tho.
If you are intereseted in making a pull request im sure @sealemar and I would be happy to review the code and if it seems like it would work we could add it.

**Comment by Dmurph24** [comment]
Ive never heard of this captcha. Personally I have never had to use it to redeem. Right now I will redeem as soon as i have enough points on my 5 accounts and they have been going for months. There could also be an option in the config to randomize when cards are redeemed if you are concerned about it looking bot-like. To me, I simply log in, go to the redeem page, click on a gift card, then click "confirm and redeem" and that is all! 

I am suggesting this here because I am not quite sure how to implement this. Just an idea I came up with.

**Comment by amayer5125** [comment]
Maybe you only get one when redeeming your first reward. I like your idea about settings for random times to redeem.

**Comment by Dmurph24** [comment]
The only time it is different is when you redeem for the first time and enter in your address and phone and confirm it, otherwise it has always just been a button click. There can be a check based on the lifetime credits and current credits and if your current credits are less than the lifetime then the reedem is good to go. But yes, it sounds like it could be useful. Unfortunately I don't think I have enough background to develop this myself.

**Comment by sealemar** [comment]
That may be not as easy as it might sound. Bing! most likely employes some JS techniques to make sure that an actual human is redeeming points. To me the benefit doesn't satisfy the amount of effort.

**Comment by Dmurph24** [comment]
Maybe it doesnt, but I thought I mention it just to be safe!
