### ISSUE TITLE
onScriptFailure: empty range for randrange() (0,0, 0)

### ISSUE THREAD

**Issue by andrewc2** [sealemar/BingRewards#132]
Script: 3.9.0
Python: 2.7.3
Raspian

Occasionally the script will run and then provide this error in the email: onScriptFailure: empty range for randrange() (0,0, 0) sometimes it happens before any accounts have ran, this time it happened after two accounts finished.

**Comment by lay295** [comment]
Same here, full traceback

Traceback (most recent call last):
  File "./main.py", line 300, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "./main.py", line 298, in <module>
    __run(config)
  File "./main.py", line 223, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "./main.py", line 210, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "./main.py", line 183, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "./main.py", line 60, in earnRewards
    results = bingRewards.process(rewards, verbose)
  File "./pkg/bingRewards.py", line 393, in process
    res = self.__processSearch(r, verbose)
  File "./pkg/bingRewards.py", line 335, in __processSearch
    ig_link_num = random.randint(0, ig_max_rand)
  File "/usr/lib/python2.7/random.py", line 241, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 217, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)

**Comment by Dmurph24** [comment]
I have also been having this problem

**Comment by amayer5125** [comment]
I wonder if Bing is returning different search results pages.
I read over the code and the only way I can think for this to come up is if the search pattern is returning no results.
would you guys be willing to try some code seeing as I dont get the error and have no way to test it?

**Comment by amayer5125** [comment]
Can you guys try [fix_rand](https://github.com/amayer5125/BingRewards/tree/fix_rand) to see if it fixes the problem? If it outputs a file can you upload to pastebin so I can see it?

**Comment by andrewc2** [comment]
I've updated the script and will see if I have the errors again. It happened randomly so I'll update if the error returns.

**Comment by feedmewifi** [comment]
this happened to me

**Comment by PlasmaPower** [comment]
@feedmewifi Try @amayer5125 's [fix_rand branch](https://github.com/amayer5125/BingRewards/tree/fix_rand).

**Comment by jcelliott** [comment]
I've been having the same issue. I'll try the fix and let you know what happens.

**Comment by amayer5125** [comment]
@jcelliott @feedmewifi @andrewc2 Have you had any luck with my fix_rand branch?

**Comment by jcelliott** [comment]
Looks like it's working for me. You might want to remove the `Searches Found:` print statement or put it in an `if verbose:` block before merging.

**Comment by amayer5125** [comment]
That was more for debug. I would take that out. Have you gotten any warning saying to check the html file?

**Comment by andrewc2** [comment]
I haven't had any errors since switching to this thanks!

**Comment by jcelliott** [comment]
> Have you gotten any warning saying to check the html file?

Nope.

**Comment by amayer5125** [comment]
I believe Bing was just running a test or something and then decided not to implement it. I will submit this patch as it adds a check to make sure search results are there instead of assuming you will always get search results.
