### ISSUE TITLE
Possibility of SOCKS protocol for proxy?

### ISSUE THREAD

**Issue by WolfEdge** [sealemar/BingRewards#136]
Is there a possibility of this happening, or is it too difficult to implement?

**Comment by amayer5125** [comment]
not against the idea, but what would a use case be?

**Comment by WolfEdge** [comment]
Personally, I don't like the idea of using public proxies. The only proxy I have access too which I've paid for is a SOCKS one. However, I'm having to run all my Pi's traffic through a VPN I'm paying for, which I'd rather not do. If I could take advantage of the SOCKS proxy that'd be great.

In addition, why not? Gotta love a bit of flexibility in programs. However, I understand that it's not easy to implement and I'm happy enough using the VPN. Thanks to @sealemar I'm making a bit of money on the side, doing nothing!

**Comment by amayer5125** [comment]
Flexability is a good thing as long as it isnt too complicated for average users.
The concern I always had with proxies are that bing is more likely to block you because if more then 2 or 3 users use the same proxy it looks like you are exceiding your "per household" use limits.

If you know python and would be willing to get some rough code together im sure @sealemar and myself would be willing to help you out.

**Comment by WolfEdge** [comment]
Sadly I don't have any experience with Python. And I understand what you mean. Thanks for the help though.

**Comment by sealemar** [comment]
I agree with @amayer5125 - if someone would like to invest _potentially_ very significant time and effort to implement that - we'll be happy to review, however I personally, like @amayer5125, unfortunately don't have enough resources to implement everything.

**Comment by PlasmaPower** [comment]
Any reason why you can't use a wrapper like tsocks? I haven't tried it, but I see no reason why it shouldn't work.

**Comment by WolfEdge** [comment]
@sealemar - Understood. I don't really mind sticking with the VPN for now. Just trying to figure out how to channel the traffic from Python scripts through the VPN only.

**Comment by amayer5125** [comment]
It doesnt seem like there is much interest in this topic. Plus it is solved with a VPN.
