### ISSUE TITLE
Connection Reset by Peer?

### ISSUE THREAD

**Issue by Dmurph24** [sealemar/BingRewards#138]
Every so often I receive the "Connection Reset by Peer" error and the script "retries" the account. This happens just frequently enough to become unstable and not run every day. What is the problem with this? Does it have to do with my internet connection?

**Comment by amayer5125** [comment]
I dont believe I have ever gotten this error while running BingRewards. Does it run any searches? or does it just fail straight away?

**Comment by EMSww** [comment]
Same here. Totally random. However the script just skip the account http://i.imgur.com/dRiFN8H.png

**Comment by amayer5125** [comment]
@EMSww did you change any of your timing settings in config.xml? I have never experienced this problem. Are you maybe running the script on wifi and your connection drops out for a second?

**Comment by EMSww** [comment]
@amayer5125 Yes I did change the timing. Usually when the internet connection drops, the script just pauses for me. I'm using googleTrends.

**Comment by sealemar** [comment]
That may be whatever, but it is originated on the backend. [StackOverflow](http://stackoverflow.com/a/1434506/2147244) talks about that. An example could be the server is throttling the activity from the IP address
