### ISSUE TITLE
Can't figure out how to get cronjob to run properly

### ISSUE THREAD

**Issue by WolfEdge** [sealemar/BingRewards#140]
For a while now I've been trying to get the script to run automatically. I've done some Googling, looking around on @sealemar's articles, comments on those articles, closed issues, experimentation, etc.. I really can't get this to work. 

So far, I've got it to the stage where it acually runs the script, and make a '.log.gz' file with the date and what happened when the script ran. Keep in mind that the script runs absolutely swimmingly when executed manually! It's great.

I've looked through the troubleshooting guide.
My version of the script: 3.9.0 from March 27, 2015
I'm using Raspbian on a Raspberry Pi. 
My python version is 2.7.3, but the crontab uses 'python2'.

My crontab:
```
SHELL=/bin/bash
PATH=/bin:$PATH
LOCAL_CONFIG_DIR=/home/bingrewards/etc

0   1   *   *   *   sleep $(($RANDOM \% 300))m && /usr/bin/python2 /home/bingrewards/bin/main.py 2>&1 | gzip > /home/bingrewards/var/log/bingrewards/`drds/`date "+\%Y-\%m-\%dT\%H:\%M:\%S"`.log.gz
```
The contents of the log:
```
/home/bingrewards/bin/notify/onComplete.sh: 1: /home/bingrewards/bin/notify/onComplete.sh: dirname: not found
onComplete: account = Live_x, points = 0, retries = 3, totalPoints = 347, lifeCredits = 347, ifStatement = 'p ne 16'
/home/bingrewards/bin/notify/onComplete.sh: 24: /home/bingrewards/bin/notify/onComplete.sh: cannot create /log.log: Permission denied
/home/bingrewards/bin/notify/onScriptComplete.sh: line 4: dirname: command not found
2015-05-26 04:52:02.2 - script started
--------------------------------------------------------------------------------

Connection reset by peer.

For: Live - x

--------------------------------------------------------------------------------
retry #2
Connection reset by peer.

For: Live - x

--------------------------------------------------------------------------------
retry #3
Live - x
Result 1/6:
-----------
name        : Trivia challenge
url         : http://www.bing.com/search?q=US+colleges&raid=quiz&rnoreward=1&roid=quiz_MQ_13
progressCur : 0
progressMax : 3
progress %  : 0.00%
description : Earn a credit for each correct answer. Don't know it? Search for it!
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn


Live - x

Points before:       347
Points after:        347
Points earned:         0
Lifetime Credits:    347

--------------------------------------------------------------------------------
Total points earned: 0

2015-05-26 04:57:22.3 - script ended
```

I apologise in advance if there's something obvious I'm missing, or if I haven't done enough homework. I've looked up what I can so far, and made my own changes. For example, not using the PATH variable for the whole thing, as I discovered that gzip + sleep and python2 are in different directories. 

Any help with this would be greatly appreciated.

**Comment by amayer5125** [comment]
Did you redact your email or in your config is the account labeled `as Live_X` under `<scripts>`?

**Comment by WolfEdge** [comment]
@amayer5125 Yep! I don't want people to know my email so I changed all appearances of it to x. If it's confusing, I can change it to something like email@email.com.

**Comment by amayer5125** [comment]
No i just think that is the default so I wanted to make sure you actually changed it. I dont use the scripts to much. Ive only worked on the search functionality of this script so I just wanted to check the easy stuff. @sealemar might be able to help more then I.

**Comment by sealemar** [comment]
```
$ which dirname
> /blah

cronjob:
PATH=/bin:/blah:$PATH
```

**Comment by WolfEdge** [comment]
Hi, thanks for your response. Sadly I was recently banned from Bing Rewards so I won't be able to test this.

**Comment by sealemar** [comment]
You don't have to run the script to test that. Instead of

```
0   1   *   *   *   sleep $(($RANDOM \% 300))m && /usr/bin/python2 /home/bingrewards/bin/main.py 2>&1 | gzip > /home/bingrewards/var/log/bingrewards/`drds/`date "+\%Y-\%m-\%dT\%H:\%M:\%S"`.log.gz
```

Do

```
0   1   *   *   *   sleep $(($RANDOM \% 300))m && echo `date` blah > /tmp/blah.txt
```

and see if the file is created. You could also remove the sleep completely for testing
