### ISSUE TITLE
Help with getting report to print

### ISSUE THREAD

**Issue by feedmewifi** [sealemar/BingRewards#141]
How does one get the script to print the big report table at the end??? Also, can I keep the console window open after it finishes so I can see what the balances on my accounts are?

**Comment by amayer5125** [comment]
@feedmewifi do you run the script from a cron job or do you run it manually?

**Comment by feedmewifi** [comment]
manually

**Comment by amayer5125** [comment]
If you run more then 1 account it will output the table at the end of all the searches

**Comment by feedmewifi** [comment]
I run four and it doesn't do that????

**Comment by TunaLobster** [comment]
What OS? Are you running it from a terminal?

**Comment by feedmewifi** [comment]
windows 7. I run it from a desktop shortcut to main.py

**Comment by TunaLobster** [comment]
That would be why it closes at the end. If you write a batch script that
pauses after running the script you will be able to read the output before
closing the window.

**Comment by feedmewifi** [comment]
and how exactly would I do that??

(>novice here)

**Comment by TunaLobster** [comment]
Here is a very basic script. Just open up notepad and save it as a .bat.

python "location of main.py with quotes"
pause

That will do what you want. This is assuming that you want added Python 2.x
to your path. Google is your friend if you have not done that yet.

**Comment by amayer5125** [comment]
@feedmewifi did you ever get this working?

**Comment by feedmewifi** [comment]
yes, it's taken care of. thanks.
