### ISSUE TITLE
Custom user-agents

### ISSUE THREAD

**Issue by EMSww** [sealemar/BingRewards#142]
Shouldn't each user have its own user agent? I think it would be more realistic than switching all the times.

**Comment by amayer5125** [comment]
I agree with this. Maybe we could put something in the config about user agents and if none are active we just pic a random one. Is this what you had in mind?

**Comment by iRobie** [comment]
The way I implemented this was here: https://github.com/iRobie/BingRewards/commit/28c588e52b317fae0919ef610b465bbc564d3930

The theory:
Each account has an account index (the order of account in config.xml)
When assigning a User Agent, the user agent is based on this account index:
+        pcagent = indexnumber%len(USER_AGENTS_PC)
+        mobileagent = indexnumber%len(USER_AGENTS_MOBILE)

That way, on each assignment, each account gets the same PC and Mobile user agent as previously assigned.

**Comment by amayer5125** [comment]
I was thinking something along the lines of:
```xml
<accounts>
    <account type="Facebook" disabled="false">
        <login>john.smith@gmail.com</login>
        <password>xxx</password>
        <useragent_desktop><![CDATA[DESKTOP USER AGENT HERE]]></useragent_desktop>
        <useragent_mobile><![CDATA[MOBILE USER AGENT HERE]]></useragent_mobile>
    </account>
</accounts>
```
This way you can set up different user agents for different accounts in your config

**Comment by iRobie** [comment]
I like your approach because you wouldn't have repeated user agents across multiple users (unless you wanted). And you could keep the config matching your real life behaviors pretty closely, without requiring new code updates.

I like my approach because it's less work for the user generating the config file.

I really like the added benefits of your approach. I think I'll do a combo - if it's assigned in the config, use that. Otherwise, grab one based on the account index.

**Comment by amayer5125** [comment]
I am working on this:
Users can enter user agent like I discribed above.
If the user doesnt enter a user agent it is selected randomly each time from the user agent list built into BingRewards.
**sidenote**: I will also be updating the user-agents to newer versions in a seperate commit.

**Comment by EMSww** [comment]
wow Thanks guys! swift as the wind!

**Comment by amayer5125** [comment]
@EMSww can you close this issue since it is taken car of?
