### ISSUE TITLE
Related Searches

### ISSUE THREAD

**Issue by bbenz3** [sealemar/BingRewards#143]
I have a suggestion but I'm not sure how easy this would be to implement. Now that the ability to randomly "click" a link is available, I was thinking that it might be a good idea to "click" on the "Related Searches" section. This would reduce the number of searches needed to meet the quota for the day. Also this would reduce the appearance of a bot.

**Comment by amayer5125** [comment]
It wouldnt be hard to click on the links but it may be trickey to count the click in the script. All the queries we use are generated before searching even begins.
