### ISSUE TITLE
How do i actually enter User agent??

### ISSUE THREAD

**Issue by jewjitsu012** [sealemar/BingRewards#150]
Not sure where the comma and parenthesis go - is this the correct format:

            <login>123456l@gmail.com</login>
            <password>11111</password>
            <useragent_desktop><![CDATA["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/7.0.1 Safari/537.73.11",]]></useragent_desktop>
            <useragent_mobile><![CDATA["Mozilla/5.0 (Linux; U; Android 4.0.2; en-us; Galaxy Nexus Build/ICL53F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30",]]></useragent_mobile>
        </account>

**Comment by amayer5125** [comment]
The tag should be ua_desktop and ua_mobile. Also you dont put any quotes and no comma at the end.
Your account tree should look something like this:
```xml
<account>
    <login>123456l@gmail.com</login>
    <password>11111</password>
    <ua_desktop><![CDATA[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/7.0.1 Safari/537.73.11]]></ua_desktop>
    <ua_mobile><![CDATA[Mozilla/5.0 (Linux; U; Android 4.0.2; en-us; Galaxy Nexus Build/ICL53F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30]]></ua_mobile>
</account>
```

**Comment by jewjitsu012** [comment]
thank you!

**Comment by amayer5125** [comment]
@jewjitsu012 If this issue is solved can you close it?
