### ISSUE TITLE
Script Stops

### ISSUE THREAD

**Issue by neeldaver** [sealemar/BingRewards#153]
I had been using an older version (early 2015), without any problems, and decided to update it.  I've setup everything like I wanted to in the config file.  When I run it, it'll start off fine. Below:
2015-07-02 16:58:22.2 - script started
--------------------------------------------------------------------------------
Live - neeldaver@gmail.com
Running PC searches

I'm using a mac and in terminal there is always a spinning wheel indicating the script is running.  The problem is after a few seconds of reaching "running PC searches" it stops.  I've waited a few minutes and checked online to see if it was working and just not displaying anything.  It wasn't working.  So then I decided to reuse my on one which I sent to trash and put back the entire folder where it was and now that is running into the same problem.  I've tried commenting out sections, but that didn't really help.  Tried disabling all accounts and see if that works and the scripts runs through the entire thing without a problem.  Also checked if my accounts were banned, they weren't.  So at this point I'm not sure what the problem is.

Python Version 2.7.6
BingRewards Version 3.12.0

Update: I'm not sure if this has to do with the "config.xml.dist" but I changed it to "config.xml"
Update 2: Even odder.  I forgot I left the script running and came back to it to see it worked.  However, for some reason it's doing everything in intervals of one hour.  Meaning, Account 1 runs --> 1 hour later starts PC searches --> moves onto mobile searches --> waits 1 hour and then starts mobile searches.  No idea why.  None of the times I've set are that long.  Also, the time between queries is ~33 seconds ± 2 seconds from what I can see.  The time set for queries is also larger than that.

**Comment by TunaLobster** [comment]
Are you using the same xml config file from your early 2915 version?

**Comment by neeldaver** [comment]
No, I downloaded the zip yesterday and only using the stuff inside.  I moved the old folder to the trash.  I thought there'd be a problem with it, so deleted both new and old folders and just started fresh.  Still with the same issues.

**Comment by amayer5125** [comment]
@neeldaver Can you post your config file with the emails/passwords removed/obscured and the commented out parts removed?

**Comment by neeldaver** [comment]
It's been starting much quicker, but still not as fast.  Still like 10 before it starts.  Which is tolerable.

<?xml version="1.0"?>

<configuration>
    <general
        betweenQueriesInterval="7.0"
        betweenQueriesSalt="56.0"
        betweenAccountsInterval="1800"
        betweenAccountsSalt="1800"
        openTopLinkRange="5"
        openLinkChance=".754"
        addSearchesDesktop="4"
        addSearchesDesktopSalt="19"
        addSearchesMobile="0"
        addSearchesMobileSalt="10" />
    

    

    <accounts>
        <account type="Live" disabled="false">
            <login>EMAIL@MAIL.com</login>
            <password>XXX</password>
        </account>
        <account type="Live" disabled="false">
            <login>EMAIL@MAIL.com</login>
            <password>XXX</password>
        </account>
        <account type="Live" disabled="false">
            <login>EMAIL@MAIL.com</login>
            <password>XXX</password>
        </account>
        <account type="Live" disabled="true">
            <login>hoho@hotmail.com</login>
            <password>xxx</password>
        </account>
    </accounts>

    <events>
        <onError>
            <retry interval="15" salt="13.5" count="3" />
            <notify cmd="/Users/USER/Downloads/BingRewards-master3/notify/onError.sh %a %p %r %P %l %i %e" />
        </onError>   
        <onComplete>
            <retry if="%p lt 16" interval="15" salt="13.5" count="3" />
            <notify if="%l gt 3000"
                    cmd='/Users/USER/Downloads/BingRewards-master3/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
            <notify if="%p ne 16"
                    cmd="/Users/USER/Downloads/BingRewards-master3/notify/onComplete.sh %a %p %r %P %l %i" />
            <notify if="%P gt 475"
                    cmd="/Users/USER/Downloads/BingRewards-master3/notify/onComplete.sh %a %p %r %P %l %i" />

            <account ref="Live_EMAIL@gmail.com">
                <retry if="%p lt 16" interval="15" salt="13.5" count="3" />
                <notify if="%l gt 750"
                        cmd='/Users/USER/Downloads/BingRewards-master3/notify/onComplete_reached.sh %a %p %r %P %l %i "Gold with %l Life Credits"' />
                <notify if="%p ne 16"
                        cmd="/Users/USER/Downloads/BingRewards-master3/notify/onComplete.sh %a %p %r %P %l %i" />
                <notify if="%P gt 475"
                        cmd="/Users/USER/Downloads/BingRewards-master3/notify/onComplete.sh %a %p %r %P %l %i" />
            </account>
            <account ref="Live_EMAIL2@gmail.com">
                <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                <notify if="%l gt 10000"
                        cmd='/Users/USER/Downloads/BingRewards-master3/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                <notify if="%p ne 31"
                        cmd="/Users/USER/Downloads/BingRewards-master3/notify/onComplete.sh %a %p %r %P %l %i" />
                <notify if="%P gt 475"
                        cmd="/Users/USER/Downloads/BingRewards-master3/notify/onComplete.sh %a %p %r %P %l %i" />
            </account>
        </onComplete>                  
        <onScriptComplete>
            <notify cmd="/Users/USER/Downloads/BingRewards-master3/notify/onScriptComplete.sh -mail" />
        </onScriptComplete>
        <onScriptFailure>
            <notify cmd="/Users/USER/Downloads/BingRewards-master3/notify/onScriptFailure.sh -mail" />
        </onScriptFailure>
    </events>

    
    <queries generator="googleTrends" />
</configuration>

**Comment by amayer5125** [comment]
Are you sure this is your entire file? You are missing a `<` after the `<?xml version="1.0"?>` to start the general tag.
And do you actually use all the things inside the `<event>` tags?

**Comment by amayer5125** [comment]
This piece right here
```xml
betweenAccountsInterval="1800"
betweenAccountsSalt="1800"
```
is putting a half hour between each account with up to an additional half hour. So pretty much this says random time between 30 and 60 min between accounts.

The defaults are:
```xml
betweenAccountsInterval="300"
betweenAccountsSalt="600"
```
Which will pause between accouts for a random time between 5 and 15 min

**Comment by neeldaver** [comment]
Does this affect how long it take before the first script to start?  Because I had left at the default time intervals but I had just be messing with the timeframe lately.  The issue still occurred at 5-15 min timeframe.  In the early 2015 version I did you all of the things inside the <events>, but in my most recent comment would be commenting out the entire onComplete event.

**Comment by neeldaver** [comment]
It seems that it was something with my editing program.  I reinstalled it and seems like it's working normally now.  It's going onto the next step with the proper times.  I reduced the time by a lot to test it and it seems to be working now.

**Comment by amayer5125** [comment]
@neeldaver glad you figured it out!
I would recommend keeping the times fairly lengthy (defalut is ok). For testing having low times is fine but if you are doing a search a second bing might start to suspect you of being a bot.
Also since this topic is resolved would you mind closing it please?
