### ISSUE TITLE
Banned Accounts

### ISSUE THREAD

**Issue by bbenz3** [sealemar/BingRewards#155]
Out of the blue I had two accounts out of five get banned today. I think it might be b/c I tried to redeem too many items yesterday and had to use the same phone number for them all due to being down a phone at the house currently. Just curious if anyone else has seen the same.

Also curious to know if anyone that has had an account get banned tried to open new accounts?

**Comment by amayer5125** [comment]
It has been a while since ive read the terms of service but I believe you are only allowed to have up-to 3 accounts with the same phone number.

**Comment by bbenz3** [comment]
Ahh well that might explain it... my phone is in the shop and so that's why I had to use the wife's number. Doh!
