### ISSUE TITLE
One account gives me error

### ISSUE THREAD

**Issue by deadman36g** [sealemar/BingRewards#158]
Here is my config

`<?xml version="1.0"?>

<configuration>
    <general
        betweenQueriesInterval="15.0"
        betweenQueriesSalt="12.0"
        betweenAccountsInterval="300"
        betweenAccountsSalt="600"
        openTopLinkRange="5"
        openLinkChance=".7"
        addSearchesDesktop="0"
        addSearchesDesktopSalt="20"
        addSearchesMobile="0"
        addSearchesMobileSalt="20" />
    

    

    <accounts>
        <account type="Live" disabled="false">
            <login>***</login>
            <password>***</password>
        </account>
        <account type="Live" disabled="true">
            <login>***</login>
            <password>***</password>
        </account>
        <account type="Live" disabled="true">
            <login>***</login>
            <password>***</password>
        </account>
    </accounts>

    
    <queries generator="wikipedia" />
</configuration>
`

The error is gives is 

`Traceback (most recent call last):
  File "main.py", line 304, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "main.py", line 302, in <module>
    __run(config)
  File "main.py", line 227, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "main.py", line 214, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "main.py", line 183, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "main.py", line 53, in earnRewards
    bingAuth.authenticate(reportItem.accountType, reportItem.accountLogin, password)
  File "pkg/bingAuth.py", line 291, in authenticate
    authMethod(login, password)
  File "pkg/bingAuth.py", line 244, in __authenticateLive
    s = page.index("<form ")
ValueError: substring not found
root@openmediavault:/media/c29e9d5b-610d-4ccb-b2d4-81a71fc90adb/NAS/OTHER/Documents/BingRewards-master# python main.py 
2015-08-11 12:18:23.2 - script started`

I have tried changing the password to something simple hoping that would fix it but it did not.

**Comment by amayer5125** [comment]
A couple questions:
1) Are you running the most recent version of the script?
2) Have you tried logging into bing through a web browser?
3) Do you always have trouble with the same account or is it a different one each time?

**Comment by deadman36g** [comment]
1) Version 3.12.0
2) Yes and I can without issue, although I do have 2FA enabled for the account
3) Always this account, others work flawlessly

**Comment by amayer5125** [comment]
I don't believe our script works with 2 factor authentication.

**Comment by deadman36g** [comment]
turned off 2FA and now it works :)

**Comment by amayer5125** [comment]
@deadman36g Since we figrued out this was a 2FA problem can you close this issue? Thanks.
