### ISSUE TITLE
Trivia Challenges

### ISSUE THREAD

**Issue by rluftw** [sealemar/BingRewards#161]
So I get this error when it approaches answering some of the trivia questions below. Does the script handle this?

Result 1/11:
-----------
name        : Trivia challenge
url         : http://www.bing.com/search?q=US+Open+Tennis&raid=quiz&rnoreward=1&FORM=ML12JG&rqw=1&roid=quiz_MQ_27
progressCur : 0
progressMax : 3
progress %  : 0.00%
description : Earn a credit for each correct answer. Don't know it? Search for it on Bing!
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

**Comment by PlasmaPower** [comment]
I'm not sure if you meant to close this, but no trivia is not supported as there is no good way to get all the answers.

**Comment by specu** [comment]
(I'm hoping to still get the conversation going on a closed ticket).
PlasmaPower: I think this is obvious, but you dont need to get the answers, you just try them all until one works - there's no down side to this at all.

Also could it be put in documentation that quizzes are not supported?

**Comment by amayer5125** [comment]
Are quizes always multiple choice? When I used to do them they were multiple choice sometimes but others they were fill in the blank. And a script would not do very well with fill in the blank.

If you would like to put in the documentation that quizes are not supported and make a pull request I will merge it.

**Comment by specu** [comment]
@amayer5125 I have not seen "fill in the blank" quizz in a long time, I dont even recall one. Most of the time I just try and click all 4 answers until I get one right.

I'll learn how to make pull requests and submit it.

**Comment by amayer5125** [comment]
@specu Even if you dont know git or python you can do some research into how the quiz works and post it here. If you find enough info it might make it easier for someone else to make the code changes.
