### ISSUE TITLE
Updated now "Cannot find the specified path"

### ISSUE THREAD

**Issue by jewjitsu012** [sealemar/BingRewards#165]
I downloaded the new update and replaced all my folders except the config.xml, the program has been working since I last downloaded last month, but now the main.py executes, logs in then logs right out. 

It's giving me the Cannot find the specified path error message, I googled and read through issues for this, tried changing the events path, tried commenting out events, those didn't work.

**Comment by amayer5125** [comment]
Do you have the absolute newest version? If so there is a bug that prevents the script from running at all. There is a pull request #164 to fix it though.

**Comment by jewjitsu012** [comment]
I downloaded the "newest" version last night 9pm PST, so if that's the one I screwed up copied the files over the old without backing them up ( i know i know). 

Is there any way to download the older version? I didn't keep a backup of the last version :(

thanks @amayer5125

**Comment by amayer5125** [comment]
In *pkg/queryGenerators/wikipedia.py* on **line 78** if you change `x.trim` to `x.strip` this should fix your problem until the pull request is accepted.

**Comment by jewjitsu012** [comment]
jeebus - that did it - thanks @amayer5125 probably seemed so simple to you lol. i need to learn python.
