### ISSUE TITLE
Further obfuscation 

### ISSUE THREAD

**Issue by shaun10** [sealemar/BingRewards#166]
In order to further strengthen obfuscation efforts, I wanted to bring up two ideas I had and see if the community thinks they would be advantageous. 
1. Sometimes intentionally not earn all points available.
2. Interweave all search types (Bing, Google, Wiki). As done with the upper and lower bound delay, extra searches, link click probability. 

More often lately it seems the automation efforts are being detected. I have had a few accounts closed now. This is with using random starts, long delays between searches, <5 accounts etc.

What does everyone think about these ideas as potential development efforts?

**Comment by amayer5125** [comment]
I like idea 1. I think earning close to but not quite max points would help with obfuscation. It wouldnt set you back that much either. If you added 1 account it would more then make up for points lost. I think our "over searching" solved this problem already though. Maybe a better way is to skip clicking on some of the "extra" points.

For idea 2 it would be pretty easy to write a query generator that combined queries from all the other query generators.

**Comment by klogdog** [comment]
pretty sure they are using some machine learning to find bots. Maybe run your own machine learning algorithm and check it against your bot?

**Comment by amayer5125** [comment]
@shaun10 not sure if you are working on a query generator or not. If you arent can you close this issue?
