### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by Shah-Parth** [sealemar/BingRewards#167]
ConfigError: Corresponding account is not found for EVENTS.ACCOUNT.ref =  [emailaddress@live.com]

**Comment by PlasmaPower** [comment]
You need to disable the example accounts. Try searching for `emailaddress@live.com` in your `config.xml`. You could also post your `config.xml` with your email address and password removed and we could fix it.

**Comment by Shah-Parth** [comment]
emailaddress@live.com is just an example. 

Here is my xml file

<?xml version="1.0"?>

<configuration>
    <general
        betweenQueriesInterval="15.0"
        betweenQueriesSalt="12.0"
        betweenAccountsInterval="300"
        betweenAccountsSalt="600"
        openTopLinkRange="5"
        openLinkChance=".7"
        addSearchesDesktop="0"
        addSearchesDesktopSalt="20"
        addSearchesMobile="0"
        addSearchesMobileSalt="20" />
    

    

    <accounts>
        <account type="Live" disabled="false">
            <login></login>
            <password></password>
        </account>
    </accounts>

    <events>
        <onError>
            <retry interval="15" salt="13.5" count="3" />
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onError.sh %a %p %r %P %l %i %e" />
        </onError>
        <onComplete>
            <retry if="%p lt 16" interval="15" salt="13.5" count="3" />
            <notify if="%l gt 3000"
                    cmd='/home/BingRewards/bin/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
            <notify if="%p ne 16"
                    cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            <notify if="%P gt 475"
                    cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            <account ref="">
                <retry if="%p lt 31" interval="15" salt="13.5" count="3" />
                <notify if="%l gt 10000"
                        cmd='/home/BingRewards/bin/BingRewards/notify/onComplete_reached.sh %a %p %r %P %l %i "reached %l Life Credits"' />
                <notify if="%p ne 31"
                        cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
                <notify if="%P gt 475"
                        cmd="/home/BingRewards/bin/BingRewards/notify/onComplete.sh %a %p %r %P %l %i" />
            </account>
        </onComplete>
        <onScriptComplete>
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onScriptComplete.sh -mail" />
        </onScriptComplete>
        <onScriptFailure>
            <notify cmd="/home/BingRewards/bin/BingRewards/notify/onScriptFailure.sh -mail" />
        </onScriptFailure>
    </events>

    
    <queries generator="wikipedia" />
</configuration>

**Comment by Shah-Parth** [comment]
Lines 33,34 ( <login></login>
            <password></password>) ,51 (<account ref="">) would have account info and password, if I'm not misunderstanding it?

**Comment by PlasmaPower** [comment]
Looking at [the example config](https://github.com/sealemar/BingRewards/blob/master/config.xml.dist#L64) it looks like you might have to put `Live_emailaddress@live.com` for line 51 instead of just `emailaddress@live.com`. Also, make sure that you put your full email address (including the @live.com) on line 33.

**Comment by Shah-Parth** [comment]
Thank you. It has worked.
