### ISSUE TITLE
New Bing accounts created with lower daily point limits 

### ISSUE THREAD

**Issue by shaun10** [sealemar/BingRewards#168]
![image](https://cloud.githubusercontent.com/assets/7233643/10430899/94d8a962-70b6-11e5-839d-6d12031ec0e6.jpg)

Might this cause any issues when doing searches on account initially? I'm not sure if it goes away after a certain period or keeps lower limit constant for all new accounts going forward.

**Comment by amayer5125** [comment]
Ive had an account for a while and my limits just got lowered to 10 points per day (5 desktop, 5 mobile).
My other account is still 15 and 25. I think Bing is realizing you cant pay people to use your service and are lowering their rewards.

**Comment by amayer5125** [comment]
This script is set up to handle the max points needed already.

**Comment by shaun10** [comment]
Yeah @amayer5125  I think so. I was thinking it might have impact on extra search numbers as well might not want to stretch it by 10 queries if max is 10 for a day etc. Unfortunately, I do see Bing starting to phase this out a bit and crackdown more.

**Comment by amayer5125** [comment]
Not sure if this is just coincidence or something else but the account I have set up with Chrome on Linux Desktop and Android mobile user agents is limited to 5&5 points a day. And the account I have set up with Safari on Mac Desktop and iPhone mobile user agents are still at normal 15&10 pints a day.

**Comment by shaun10** [comment]
Oh nice interesting @amayer5125 , maybe if last search is done with a certain user agent the next time bing is loaded it hold on to that limit. That could account for limit deltas we encounter.

**Comment by amayer5125** [comment]
This doesnt seem to be an issue any more. All accounts earn the same amount of points.
