### ISSUE TITLE
All accounts closed, obfuscation or number detection, IP address used?

### ISSUE THREAD

**Issue by shaun10** [sealemar/BingRewards#174]
Bing has become particularly astute to detecting automation attempts. All accounts have been closed and new accounts I try to open are usually closed before anything can actually be redeemed. Wondering if anyone else has ran into this. Also if there are any ideas on how to prevent this in the future? 

FWIW ran 3 accounts with:

    <general
        betweenQueriesInterval="24.2"
        betweenQueriesSalt="15.5"
        betweenAccountsInterval="910"
        betweenAccountsSalt="1448"
        openTopLinkRange="5"
        openLinkChance=".4"
        addSearchesDesktop="2"
        addSearchesDesktopSalt="8"
        addSearchesMobile="3"
        addSearchesMobileSalt="9" />

Also croned the start time to delay between 1-60 minutes.

**Comment by amayer5125** [comment]
@shaun10 did you have your User Agents set in the config?

**Comment by Hieysk** [comment]
@shaun10 A friend of mine has this issue as well.  My accounts however, have been running without issue for a while now (>4k bing points gathered).

Perhaps it is tied to your IP address, maybe getting that swapped out would help.

**Comment by shaun10** [comment]
@amayer5125 No I didn't have any user agent settings configured in the XML file. Does that tend to help a bit?

@Hieysk ISPs regularly change IP addresses for home networks don't they? I was thinking maybe the MAC address or phone number I use in the new challenge questions.

**Comment by Hieysk** [comment]
@shaun10 - I guess it depends on the ISP you have.  My IP address is static for my home.

A few things that I try to do:
* When starting new accounts, don't create 4-5 new accounts in one session.  Spread it out over a week.
* I attempt to make my email address appear to be from one family (Husband, Wife and a few teenagers)
* If you have previous accounts that have suffered from a ban, then use a different cell phone to redeem.
* If you receive a ban, challenge their customer support as to why you were banned.  I have done this on my original account and after a yearlong ban they reinstated the account.  I think sometimes it helps your case as you are obviously a human trying to interact with their support staff to inquire about your account status.
* When you redeem, only do one account per day.
* When you redeem, I try to do it from a different IP address (work) than from where the script runs (home).
* Log in to each account periodically and play the trivia games and click on some of the extra point things they have. (+1 humanness)
* Keep track of the information that you use to create your accounts.  If you ever contact customer support they may ask specific questions about your profile.
* I tried to use yahoo addresses, as you can create sub email accounts that all of the incoming mail rolls into one account (for receiving reward emails), This didn't work as bing sniffed out these pretty quick.  So stick with normal email accounts from AOL, Gmail, outlook.com etc...
* Don't get greedy.  The only real time I had issues with banned accounts is when I tried to >4 accounts.

Just a few things that I have learned in the past.

**Comment by amayer5125** [comment]
I dont think anyone has had this issue in a while. No need to keep the issue open.
