### ISSUE TITLE
Script Failure: Empty Log

### ISSUE THREAD

**Issue by iAmWillX** [sealemar/BingRewards#178]
Hey Guys, I love this script but lately, it hasn't been working out for me.

This is using the latest commit.

Here is an example of whats happening.
![image](http://i.imgur.com/xSNY3nH.jpg)

Thanks!
- iAmWillX

**Comment by aaronjohnleonard** [comment]
+1 Exact same issue

**Comment by breatheforme** [comment]
+1 Same thing for me as well

**Comment by iAmWillX** [comment]
Bump. Any Clues?

**Comment by Amazingred** [comment]
Yeah.  Log into your live account manually and check to see if they are trying to prompt you with something.  Phone verification or something to that effect. If thats what it is once you get past that prompt successfully the script will start working again.

**Comment by aaronjohnleonard** [comment]
I just tried logging in and I didn't have any sort of prompt waiting for me. So I went back to the script and it now works. Hmm.

**Comment by breatheforme** [comment]
I did the same but still having the issue.
