### ISSUE TITLE
HTTP Error 302 causes script to not search for account

### ISSUE THREAD

**Issue by andrewc2** [sealemar/BingRewards#179]
error = 'HTTP Error 302: Found - Redirection to url 'microsoft-edge:https://www.bing.com/rewards/dashboard?FORM=ML12VZ' is not allowed'

Been running into this error on accounts randomly, some days it does it, and it isn't a consistent account either. Just updated the other day to fix issue 176

**Comment by KevZho** [comment]
+1, getting the same error. My config.xml has my desktop user agent as the Edge one if that helps.

**Comment by amayer5125** [comment]
is the user agent wrapped in CDATA block?

**Comment by KevZho** [comment]
Yes, I have it wrapped in a cdata block

**Comment by amayer5125** [comment]
If so might be some bing thing that blocks Edge? Try changing it and see if it still happens

**Comment by andrewc2** [comment]
For me I haven't set a user agent

**Comment by Hieysk** [comment]
Happening to me as well..  (today 2 accounts out of 4 suffered this fate).

I am not using a user-agent in my config.xml.

**Comment by amayer5125** [comment]
Login through a regular web browser works?

**Comment by Hieysk** [comment]
Yes, I just logged in as one of those accounts that failed.  All looks fine from an account standpoint.  Also shows 0 searches for both desktop and mobile today.

**Comment by breatheforme** [comment]
+1

**Comment by amayer5125** [comment]
This seems to be a pretty common issue. I wonder if bing is rolling out some new interface.
If you run the script again right after it fails does it still fail?
When you log in throught the web browser does it look any different then your other accounts? Even check for very subtle things.

**Comment by andrewc2** [comment]
Not typically, it will fail multiple times in a row. I haven't seen any
changes in the web browser.

Andrew Christensen

**Comment by mauCassandra** [comment]
I'm having this issue for the past few hours..any fixes?

**Comment by slango20** [comment]
This is the same exact issue as #169 with a different cause, pull #173 had this fixed a while ago but it popped up again with a new name: "Time for a change" instead of "Earn more credits." fixing that is trivial (also apply #173 as well, it's still relevant, not sure why it's not in master yet)

**Comment by sealemar** [comment]
#173 has been merged as a part of #192 . Please, confirm the issue is not happening again and close it.

**Comment by amayer5125** [comment]
Is anyone in this thread still experiencing these issues? We have done a couple updates over the past week.

**Comment by andrewc2** [comment]
I think this is good now.
