### ISSUE TITLE
Searches are running but not getting any points

### ISSUE THREAD

**Issue by aidenator** [sealemar/BingRewards#181]
At the end of each cycle I only get 3 points from the dashboard links I believe, I can see that it's running the searches but I don't get any points from it. Anyone else have this issue?

**Comment by amayer5125** [comment]
I had this happen for 2 days in a row. It has returned to normal now. When you log into your account what type of points did you earn?

**Comment by aidenator** [comment]
I get 3 of the easy "Daily Offer" points where you just have to click on the link. I'll update this in a few days and let you know if it starts working again.

**Comment by drapermache** [comment]
I can verify the same issue. No points have been added for several days. Ran the script manually, and the searches were marked successfully, but looking into my account, the points were not added to my account.

**Comment by Shah-Parth** [comment]
Same issue with error  "Temp Account ban. User was not successfully signed in."

**Comment by amayer5125** [comment]
@Shah-Parth I think this is a different issue. This seems to be a login issue.

**Comment by Hieysk** [comment]
Getting same issue here on all accounts.
(error = 'Temporary account ban: User was not successfully signed in.)

I have not changed login credentials.
I have verified that I can login via browser. (I get no weird pop ups or anything, account is in good order).

Hieysk

**Comment by amayer5125** [comment]
I believe they changed the login somehow. I dont have time to look at it right now but I can check it out later.

**Comment by drapermache** [comment]
@amayer5125,If it were a login issue, wouldn't we not get the dialy 3 points? Seems to be limited to searches.

**Comment by amayer5125** [comment]
Like I told @Shah-Parth I believe the Temp ban is a different issue.
The "extra points" I get returned after the Temp Account Ban issue are things like "Join Bing Rewards. Its Free!". So that leads me to believe Im not acctually logged in.

**Comment by PlasmaPower** [comment]
FYI, the temp account ban detection is simply if the text "You are not signed" appears in the HTML. Source: https://github.com/sealemar/BingRewards/blob/master/pkg/bingRewards.py#L129

**Comment by aidenator** [comment]
Okay, so it hasn't gotten any better. Now I'm getting the same error as @Shah-Parth 
"BingAccountError: Temporary account ban: User was not successfully signed in."
Let's hope it's just a different way of signing in and it can be remedied.

**Comment by msea1** [comment]
Same issue here. No points for last 2 days and seeing the same BingAccountError output

**Comment by jabbowaki** [comment]
Also seeing the 'temporary account ban' error.

**Comment by camy142** [comment]
Same as mentioned above, has been getting 'temporary account ban' the past two days.

**Comment by slango20** [comment]
Verified that the server says the user is not logged in, I configured my local copy to dump the page if it failed to log in, looked at it in a browser, and it indeed had "not signed in" plastered across the page. nothing about being banned though, and a regular browser still works just fine for login and collection

**Comment by camy142** [comment]
@slango20 from what you are saying, does that mean the script isn't connecting to the server to sign in with the credentials?

**Comment by blakekl** [comment]
It means that something in the authentication process has changed (by bing), so the script is trying to login incorrectly and failing.

**Comment by slango20** [comment]
@camy142 No, it's connecting to the server and obtaining the page properly, but the page has "not logged in" plastered across the page

**Comment by camy142** [comment]
@blakekl so the script will have to be modified to adapt the 'changed' authentication process by bing?

**Comment by PlasmaPower** [comment]
@camy142 Yes, specifically the authentication part (`BingAuth`).

**Comment by blakekl** [comment]
In the mean time, you may want to disable the auto-run stuff until this gets figured out.

**Comment by HmmU** [comment]
The "Temporary account ban" error mentioned in this issue has been fixed in pull request #183

**Comment by Shah-Parth** [comment]
Can someone please merge it with master branch?

**Comment by amayer5125** [comment]
@Shah-Parth The fix has been merged.
