### ISSUE TITLE
BingAccountError: Temporary account ban: User was not successfully signed in

### ISSUE THREAD

**Issue by camy142** [sealemar/BingRewards#182]
I know someone had this issue before but I can't find the reason behind it. Not to be mistaken, my account isn't banned by Bing! I haven't changed anything settings (computer nor the script) and I know it works because I didn't have this issue 2 days ago. Help?

**Comment by PlasmaPower** [comment]
This is being discussed over in #181, but should possibly be moved to a separate issue like this one

**Comment by jgkamat** [comment]
+1, seeing this as well

**Comment by HmmU** [comment]
This has been fixed in pull request #183

**Comment by amayer5125** [comment]
@camy142 This has been fixed. You can close the issue.
