### ISSUE TITLE
Searches not counting?

### ISSUE THREAD

**Issue by msea1** [sealemar/BingRewards#185]
I've noticed for the past couple days that my searches aren't counting. Yes, I'm up to date on the code and also have pull req #173 in there as well. Here's some of the weird behavior that I'm seeing:

- I can log in to the accounts manually just fine. Can get points manually just fine. Can redeem awards just fine.
- I see no errors when the script runs, it just keeps failing to record any points and retries.
- I am earning the ~3 points per day from the one-off links. Those are being added to the accounts just fine, which makes me think it's not a auth or log-in issue?
- When I tried running locally, it recorded the searches. What's failing is runnings from my server. Never failed before.

So, maybe it's an IP issue with the server? But if so, no errors and getting the ~3 points per day seems confusing.

**Comment by tsdg112** [comment]
I'm having the same problem, but just on one of my accounts.  Here is the log...

Result 1/8:
-----------
name        : Search and earn
url         : http://www.bing.com/news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&rnorewa
rd=1
progressCur : 0
progressMax : 15
progress %  : 0.00%
description : Earn up to 15 credits per day, 1 credit per 2 searches. Start with
 US News.
   Error    :   true
   Message  : Don't know how to process this search
   Action   : warn

It doesn't recognize that it needs to run PC Searches, and doesn't try to run any,

**Comment by andrewc2** [comment]
Looks like bing changed the way it counts searches. On my dashboard they're only listing one type of search not breaking out desktop and mobile.

**Comment by amayer5125** [comment]
I was having this issue a coulple days ago but my account is back to normal. are you guys still experiencing this?
@andrewc2 I have a combined score and a broken our score. can you screenshot your points dropdown?

**Comment by andrewc2** [comment]
http://i.imgur.com/fFKsN7c.png I manually did the searches today as the script only got 4 points

**Comment by mihir3535** [comment]
For the past few days the script has been working fine for 3/4 of my accounts, with one of them having the issue described here. Today, it seems like none of the accounts are working for me. Even the "earn 1 credit" links don't seem to be working.

**Comment by tsdg112** [comment]
I have fixed my problem with the Search and earn.  Here is a diff -u of the changes.  Somebody braver than me can enter a pull request.
[181fix.txt](https://github.com/sealemar/BingRewards/files/168089/181fix.txt)

**Comment by msea1** [comment]
I just tested @tsdg112 diff on my auto search and still only get the 3 Earn and Explore points. No points for searches, which for my account are still on the old PC and Mobile split. 

However, I'm still guessing it's an IP or some other non-code issue for me because the server-based run gets the Earn and Explore only, but the local-machine-based run gets the search points. I'm unsure how to go about debugging it on the server level though. I'll have to devote some time in the future to figuring out where to throw breakpoints in.

**Comment by andrewc2** [comment]
@msea1 It could be that the diff doesn't work with the old PC/Mobile split and only works on the new all in one search? I would try that code on mine if I knew how to integrate it.

**Comment by jfish3** [comment]
Any updates on this? I actually have different wording than @tsdg112 had in their diff ("Earn 1 credit per 2 searches on PC or mobile, up to 10 credits per day."), but changing the line didn't seem to work either.

**Comment by maverick915** [comment]
I am just starting this for the first time and can't figure out what I'm doing wrong.  Is this tool just dead?

**Comment by amayer5125** [comment]
@maverick915 I use this tool daily. I believe some accounts were moved to a new layout and that could be the problem. I have not been moved to the new layout so I cannot look at what code changes need to happen to support it.

**Comment by andrewc2** [comment]
If I let one of the contributors borrow my account which uses the new point system, they could make an update for those of us with the new point system?

**Comment by RedOrion** [comment]
I have the mobile and pc searches separate. Is that the new or old system?

**Comment by andrewc2** [comment]
Separate searches is the old way. The script works fine with pc and mobile searches separate though.

**Comment by jtrevag** [comment]
@andrewc2 How do I initiate separate searches? Looks like searches aren't counting for new accounts... going to look into it sometime today (if work permits :P)

**Comment by andrewc2** [comment]
@jtrevag There is no way to re-separate the searches once Bing switches an account :(

**Comment by jfish3** [comment]
Any updates on this issue? I noticed there was some activity...

**Comment by amayer5125** [comment]
@jfish3 are you still having problems searching? Does your rewards flyout look like [this](http://i.imgur.com/fFKsN7c.png)?

**Comment by msea1** [comment]
I just tested with a fresh pull and mine is now working again on server. I still have the separate PC/Mobile dashboard. 

I'll give it another day or two to confirm some automatic/cron runs. But as far as I see, my issue is fixed.

**Comment by jfish3** [comment]
@amayer5125 Still having problems with the search... my rewards flyout looks like this
<img width="651" alt="screen shot 2016-06-27 at 3 58 27 pm" src="https://cloud.githubusercontent.com/assets/18254416/16395678/ce0af3a2-3c80-11e6-8760-f1616b539454.png">

**Comment by amayer5125** [comment]
Was that taken from your [dashboard](https://www.bing.com/rewards/dashboard) or from clicking on your points in the upper right of your screen?

**Comment by amayer5125** [comment]
This is the page our script really cares about: http://www.bing.com/rewardsapp/flyoutpage?style=v2
Can you click through and see if there is a "PC search" and a "Mobile search" slide?

**Comment by jfish3** [comment]
Ah, that was from the dashboard. Here's the pages you mentioned:
<img width="273" alt="screen shot 2016-06-27 at 4 12 15 pm" src="https://cloud.githubusercontent.com/assets/18254416/16395938/02b91b50-3c82-11e6-9468-823f11a60857.png">
<img width="402" alt="screen shot 2016-06-27 at 4 10 53 pm" src="https://cloud.githubusercontent.com/assets/18254416/16395939/02ba408e-3c82-11e6-9a15-eb03e17cfe1a.png">

**Comment by amayer5125** [comment]
Have you searched manually? Can you get all 15 points searching on desktop? or all 15 searching on mobile?
It seems really weird that is says 15 credits per day, but then lists 0/30 DAILY SEARCH up higher. Does it explain anywhere how to get 30 points per day? I think I know how to fix it we just need to kno w the best way to get the most points.

**Comment by jfish3** [comment]
Yep, manual searches work. I think it's just the wording is an edge case the script might not handle. It doesn't even attempt the searches with the script.

I think the way my account is setup is its a point for every 2 searches, so you need 30 total searches go get all 15. Not sure if anyone else's is setup this way?

**Comment by andrewc2** [comment]
Yeah it's 1 credit per 2 searches for me, http://i.imgur.com/jIo5NNj.png is what that looks like for me

**Comment by amayer5125** [comment]
@andrewc2 how did you get your 30/30? was it all desktop? or half desktop half mobile? all mobile?

**Comment by andrewc2** [comment]
They were all desktop

**Comment by amayer5125** [comment]
@jfish3 @andrewc2 I didnt test [this](https://github.com/amayer5125/BingRewards/tree/new_points) yet but I believe it should work. If you could test it and let me know if it works that would be great!
If you get any errors please record them and I will take a closer look at them tomorrow.

**Comment by andrewc2** [comment]
Will do @amayer5125

**Comment by jfish3** [comment]
@amayer5125 Not working here unfortunately :(

```
❯ ./main.py
2016-06-28 21:40:51.2 - script started
--------------------------------------------------------------------------------

Live - [email address]

For: Live - [email address]

--------------------------------------------------------------------------------

Full log:
---------
Empty log
onScriptFailure: -mail
```

**Comment by andrewc2** [comment]
I got this in my email: onScriptFailure: 'NoneType' object has no attribute 'group'

And this is the log looks the same as @jfish3

**Comment by amayer5125** [comment]
@jfish3 @andrewc2 ok guys I messed up the regex a little. [Here](https://github.com/amayer5125/BingRewards/commits/new_points) is the fixed version. Same thing... test and report. Thanks :)

**Comment by andrewc2** [comment]
@amayer5125 Working here.

**Comment by jfish3** [comment]
@amayer5125 working here for me as well! Thank you very much!

**Comment by amayer5125** [comment]
Ill put a pull request together and get it merged with the main project.
