### ISSUE TITLE
Bing changed their points system, not accruing points anymore

### ISSUE THREAD

**Issue by Cryson** [sealemar/BingRewards#186]
Bing has changed some of my accounts to the below:
[http://i.imgur.com/YD0tK6g.png](http://i.imgur.com/YD0tK6g.png)

The accounts that have been "upgraded" essentially are not getting points anymore.

**Comment by amayer5125** [comment]
I think they are rolling out a new system. My points still go through and when I log in I get the old points view. It may just be a matter of time until one of the Devs gets the new interface that they can put new code together.

**Comment by shaun10** [comment]
BingRewards is changing unfortunately. Using points for rewards now is mostly connected to Microsoft store. There is really only one reward left worth anything.

**Comment by amayer5125** [comment]
This was fixed by #195
