### ISSUE TITLE
Queries not returning results

### ISSUE THREAD

**Issue by duddles** [sealemar/BingRewards#188]
Just yesterday I started getting

Warning!: Query returned no results, check error_*.html file for more information

When I check the error file it looks like a normal search results page with results.

Any ideas for fixing this?

It still seems to be counting the searches despite the warnings

**Comment by amayer5125** [comment]
Do you get it for every result or just some?
I know I get it for any query that returns an image or info section as the first result.

**Comment by duddles** [comment]
Every result, same as RedOrion posted in #189

**Comment by amayer5125** [comment]
I get that same error sometimes. Do you still earn points? Even when I get messages like that I still earn points. I think we need to wait for bing to finish making what ever change it is going through right now and once it happens on everyones account we can change our code to match.

**Comment by duddles** [comment]
I still am earning points

**Comment by RedOrion** [comment]
@duddles I'm still earning points as well.

**Comment by jtrevag** [comment]
I am having this issue as well. But not earning any points :(

**Comment by duddles** [comment]
Seems to be working okay now so I will close the issue
