### ISSUE TITLE
Temporary account ban: User was not successfully signed in.

### ISSUE THREAD

**Issue by pavanpalaksha** [sealemar/BingRewards#190]
I started seeing temporary account ban again. But, I am able to successfully login through browser. Is anybody else seeing this as well?

**Comment by amayer5125** [comment]
I wonder if they changed something with the login. My first 2 accounts had no problems. Then my 3rd one wouldnt work. I tried from 2 different IPs. I know sometimes they block IPs temporarily.

My best guess is they changed the login. Not sure when I will be able to look into this.

**Comment by pavanpalaksha** [comment]
Well. I don't think they blocked the IPs. I am able to fetch points by logging in from browser. They have certainly changed the login mechanism. Let me take a look today evening and see if I am able to figure out something.

**Comment by bbmak** [comment]
Yes, I am having the same issue.

**Comment by aaronjohnleonard** [comment]
Same issue here

**Comment by tgsong** [comment]
Also same issue, any fix for this?

**Comment by aaronjohnleonard** [comment]
Microsoft sent me an email saying that someone else had accessed my account, and they made me reset my password. I did and changed it in my config.xml, but I am still getting the same issue.

**Comment by jeshuamj2** [comment]
Having this issue as well. Had it on 1 of 2 accounts yesterday, now both not working. Help please!

**Comment by amayer5125** [comment]
Has anyone started looking into this? I am looking into it now and dont want to repeat anyones work.

**Comment by amayer5125** [comment]
I didnt get too far with getting this to work but I found that Bing changed their post fields and PPSX.
Here is what I got so far: https://github.com/amayer5125/BingRewards/commit/97d10fb09621d94e764a8be44c0cc5081393c306

**Comment by ViperBots6210** [comment]
Been having the same problem for 3 days now, I'll try having a look at the new auth system with bing

**Comment by AdamBusch** [comment]
Been having this problem for 3 days now, I'll try having a look at bing's new auth system

**Comment by amayer5125** [comment]
@AdamBusch Ive been looking into it. I would love some help through. If you want to view my work [here](https://github.com/amayer5125/BingRewards/commit/97d10fb09621d94e764a8be44c0cc5081393c306) as a jumping off point I would love to collaborate on this.

**Comment by jeshuamj2** [comment]
That modified bingAuth.py seems to have done the trick. Works on both my accounts!

**Comment by sinkillerj** [comment]
I concur, your PR seams to do the job nicely amayer.
