### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590

### ISSUE THREAD

**Issue by rewardone** [sealemar/BingRewards#210]
Apparently Python 2.7.9+ added certificate verification for HTTP requests by default. I'm not sure how robust urllib2.Request is in Python 2, but one answer seems to be appending a verify=False flag to the request. Another solution is to just submit a proper HTTPS request.

See link for additional information [http://stackoverflow.com/questions/30704894/why-i-receive-certificate-verify-failed-from-google-adwords-api](url)

A temporary non-code solution is to just use Python 2.7-2.7.8 before this behavior was added.

**Comment by specu** [comment]
would the following work for you?

+++ b/pkg/bingRewards.py
@@ -10,7 +10,7 @@ import cookielib
 import random
 import time
 import urllib
-import urllib2
+import urllib2, ssl
 import importlib
 import re

@@ -56,6 +56,10 @@ class BingRewards:
             config.proxy - proxy settings (can be None)
         """

+        ctx = ssl.create_default_context()
+        ctx.check_hostname = False
+        ctx.verify_mode = ssl.CERT_NONE
+
         self.betweenQueriesInterval = float(config.general.betweenQueriesInterv

(not a valid diff so you have to add those/alter those lines manually

**Comment by amayer5125** [comment]
I don't believe anyone else has run into this. Since it has been almost a year I am closing.

**Comment by specu** [comment]
I keep getting it fairly often, but retries are successful.
