### ISSUE TITLE
Separate Proxy Per Account

### ISSUE THREAD

**Issue by FunkyEssence** [sealemar/BingRewards#211]
Hello. I'm trying to find out how to add a proxy to each account individually. Are the proxies currently set up to be global (for all accounts) or is there a way to add a different proxy address for each, lets say, 6 accounts?

If not, could this be easily added?

Thanks!

**Comment by amayer5125** [comment]
Im sure it could be easily added. Right now our proxy is set up pkg/bingRewards.py around [Line 73](https://github.com/sealemar/BingRewards/blob/master/pkg/bingRewards.py#L73). Im not sure how much of a demand there is for something like this but if you submit a pull request I would be happy to review it.

**Comment by FunkyEssence** [comment]
Sure. I just attempted to submit a pull request but I am unsure how to. I am not very familiar with GitHub.

**Comment by FunkyEssence** [comment]
I was thinking something like this:

`<accounts>`
`    <account` type="Live" disabled="false">
`        <login>name@domain.com</login>`
`        <password>XXX</password>`
`        <useragent_desktop>XXX</useragent_desktop>`
`        <useragent_mobile>XXX</useragent_mobile>`
**`     <proxy>111.22.33.444:5555</proxy>`**
`    </account>`
`</accounts>`

**Comment by FunkyEssence** [comment]
Closing issue.

I suppose the workaround would be to just create multiple configs with a different proxy per config file, then create a batch file to run the script multiple times, one after another.
