### ISSUE TITLE
Error Code: 500

### ISSUE THREAD

**Issue by FunkyEssence** [sealemar/BingRewards#213]
I'm receiving an error code 500 when attempting to perform mobile searches after PC searches finish. Any ideas what causes this?  

This doesn't happen to every account. Some work after retrying a couple times, and some fail after all 5 of the retry attempts (I increased the amount of retries) and skip onto the next account.

> Live - email@domain.com
> The server couldn't fulfill the request.
> Error code:  500
> 
> For: Live - email@domain.com

**Comment by baltimoron** [comment]
The following chunk of code is causing it (in pkg/bingRewards.py):

        url = bingHistory.getBingHistoryTodayURL()
        request = urllib2.Request(url = url, headers = self.httpHeaders)
        with self.opener.open(request) as response:
            page = helpers.getResponseBody(response)
        history = bingHistory.parse(page)

I tried accessing the history URL manually and it worked fine so I'm not sure what the issue is. It's not really that important so i just commented it out and replaced it with an empty set (history = set()). It doesn't seem worth the time to do a real fix.

**Comment by amayer5125** [comment]
@baltimoron The history is used because searches need to be unique. If you already searched for a term the history will ignore it when search terms are being generated.

**Comment by baltimoron** [comment]
@amayer yeah I know what it does I just doubt it's necessary as long as you're running a few extra searches.

**Comment by amayer5125** [comment]
Also as long as you are using the Wikipedia query generator you should have some pretty unique results. For a temporary work around it should work. Im starting to think BR is doing some weird things with cookies on pages we arent hitting so we are being logged out.
