### ISSUE TITLE
Request: support to process quizzes

### ISSUE THREAD

**Issue by specu** [sealemar/BingRewards#219]
I think the subject says it all.

**Comment by Vixine** [comment]
Dude write it and request a merge!

**Comment by amayer5125** [comment]
The problem with multiple choice is that we would need to try every option until we got the right one and that is very bot-like behaviour and would make detecting scripts very easy.

**Comment by specu** [comment]
Thats precisely how i do it personally since forever, no consequences. As
long as its random, youll guess correctly in 1-4 tries which is imho not
bot like.
It would be bot like to guess on first try or exact same number of tries or
keep trying after guessing the right answer.
The reward for it is 40 points a week dot dot dot - its nice to get but
would not do it if theres even a minimal risk.
In addition for edge theres new kind of quizzes where you drag and drop
answers in correct order - that would be probably touch givrn the benefit.

**Comment by amayer5125** [comment]
We will take pull requests but so far nobody has take the time to come up with a good solution for it.
