### ISSUE TITLE
Issue running script on Centos 6.8 w/ python 3.4

### ISSUE THREAD

**Issue by thanatos216** [sealemar/BingRewards#222]
The message:
I have tried the troubleshooting guide and here is what I get

Bing! Rewards Automation Script version
 ./main.py --version
  File "./main.py", line 64
    print "-" * 80
            ^
Python version
 python3 --version
Python 3.4.5

OS type
cat /etc/redhat-release
CentOS release 6.8 (Final)

On what type of searches that happens: PC / Mobile / All
All

Stack trace
 ./main.py --version
  File "./main.py", line 64
    print "-" * 80
            ^
Steps to reproduce
anytime i run main.py

**Comment by jbrobst** [comment]
The script isn't compatible with python 3, you have to use python 2. I'm not familiar with CentOS but on my debian machine there is separate `python` (for python 2) and `python3` packages and I run the script using `python main.py -v`.

**Comment by thanatos216** [comment]
Thanks,
I was able to install python 2.7 and the script worked w/ a couple of 302 errors... Centos default python is 2.6 and I thought 3 was supported because of the 2.7+ my bad... sorry for the confusion.

onError: account = Live_XXXXXXXXXXXXXXXXXX, points = 0, retries = 3, totalPoints = 0, lifeCredits = 0, ifStatement = 'None', error = 'HTTP Error 302: Found - Redirection to url 'microsoft-edge:https://account.microsoft.com/rewards/dashboard?FORM=ML1329' is not allowed'

**Comment by jbrobst** [comment]
I agree that the 2.7+ thing is kind of confusing. Eventually I might try to port it to be compatible with python 3 just as a learning experience. Looks like that 302 error is from trying to redirect to a microsoft-edge protocol link, which is tied to one of the rewards where Microsoft wants you to open edge for extra points or something; I will try to look into that.
