### ISSUE TITLE
searches not counting 

### ISSUE THREAD

**Issue by hakanaikioku** [sealemar/BingRewards#223]
I've had the script running on a cron job for over a year, but recently (past few months) have been having issues with searches not counting. I have 4 accounts active and most days these past few weeks most if not all won't count searches, I'll upload a log file tomorrow with details. I am fully updated on the script. It had happened before but usually only for a day or two a month, but it's been pretty consistently not working recently. I don't see any errors in the logs other then it not counting searches, it usually counts other rewards every when searches don't work. I can login and manually run searches and they work. Does anyone else have this problem, or any advice for trouble shooting it? Thanks!

**Comment by gnuguy** [comment]
Hi, I was experiencing the same issue last week.  I would get credit for 3 or 4 searches per account.  I increased the delay between searches and that seems have fixed the issue.
I changed:
betweenQueriesInterval="15.0" 
betweenQueriesSalt="12.0" 
to
betweenQueriesInterval="30.0" 
betweenQueriesSalt="15.0"

**Comment by hakanaikioku** [comment]
I have tried fiddling with the Queries interval and it hasn't fixed the issue. My roommate changerd his password without updating the config file so that is why the roommate1 account in the log isn't working.
Here i a log file, I can past it in if people prefer:
[bingbot_log.txt](https://github.com/sealemar/BingRewards/files/724780/bingbot_log.txt)

**Comment by hakanaikioku** [comment]
Does anyone have anything more suggestions? increasing the delays helped a small amount but I doubt doing much more will make it better, plus it will start taking more then a day to complete~

I'm not even making the minimum to keep a gold rating every month...

**Comment by hakanaikioku** [comment]
I'm still having issues with searches counting, I just looked at my Bing search history online and it doesn't have anything since PI day (3.14.2017). The script has run each day, but Bing apparently isn't seeing the searches. Logs still look like the log I uploaded, except roommate1 account is working now and it isn't reading lifetime credits anymore.

**Comment by gnuguy** [comment]
Are you able to log into your bing account through the website?  I had a similar issue with one of my friends accounts where it wasn't getting points or showing credits. When I tried to login online it made me verify the account with a txt message than worked fine again after that.

**Comment by amayer5125** [comment]
searches work in newest version.
