### ISSUE TITLE
onScriptComplete.sh not found

### ISSUE THREAD

**Issue by FadeVT** [sealemar/BingRewards#224]
I'm not entirely sure what to do here, so I am seeking help in correcting this issue.

The onScriptComplete.sh file is found in ~/BingRewards/notify

The config.xml shows the path as /home/BingRewards/bin/BingRewards/notify

I have tried leaving it as is with the incorrect path, and I have tried changing it to the correct path. Both result in this message...

`2017-01-24 07:53:17.0 - script ended
/bin/sh: 1: /home/BingRewards/notify/onScriptComplete.sh: not found
`

Any idea what could be happening to cause this?

**Comment by amayer5125** [comment]
You need your username in the path.
/home/USERNAME/BingRewards/notify/onScriptComplete.sh

**Comment by FadeVT** [comment]
Oh wow, idiot move of the century!  

Thank you VERY much for the prompt response.
