### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by elisiano** [sealemar/BingRewards#225]
Hi,
   I've tested this inside a container and it works pretty well (since I used python:2-alpine it's not able to send emails, but I guess I could look into that).

So the question is, since generating an image is pretty easy (literally a 4 lines Dockerfile), is there a plan to build an official image? The advantages of having an official image is that if you link the repo with the docker hub, you can have automated builds every time a commit is done (instead of people creating their own containers off of this repo and manually update them).

Would you like a PR for this?

**Comment by elisiano** [comment]
I do have the code ready ( https://github.com/elisiano/BingRewards/commit/ae78fd5469ea6be07042e4376d01222b26a9808b ), is there any interest in this?

Alternatively, I'll need to change the process and pull the code from the Dockerfile (which is not a big deal but we'd lose the capabilities of automated builds).

**Comment by amayer5125** [comment]
If you add directions to README and make a pull request I am willing to test this. I think a docker container would get rid of some of the python2 python3 stuff that is happening currently.

**Comment by elisiano** [comment]
Dockerfile added as part of #292
