### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by marioandluigi878** [sealemar/BingRewards#226]
From looking at this point right now there hasn't been any merges at all or even updates to the code i think we can offically declare this dead...

**Comment by ajshastri** [comment]
Well my stuff works currently. Is it dead when the product works fine?

**Comment by amayer5125** [comment]
Seems to work for me also. I dont get points every day but I just chalk that up to Bing "throttling" my IP address.

**Comment by marioandluigi878** [comment]
I guess but what about the author anyone see him on at all? I understand if it was irl stuff but the code hasn't been updated by himself in a long time so....

**Comment by Shah-Parth** [comment]
How does the PR's get merged? Seems like @sealemar has not given anyone else any permissions

**Comment by amayer5125** [comment]
@Shah-Parth There are other people besides the main author who can merge to this project. If you have a merge request you can post it and I will review it.

**Comment by amayer5125** [comment]
I believe this issue has been solved. Verdict: project not dead.
