### ISSUE TITLE
Not doing PC searching

### ISSUE THREAD

**Issue by frank777777777** [sealemar/BingRewards#231]
I downloaded the latest version. Tested on windows10, xp, and linux. I modified the xml: added account, password, and commented out events onComplete section. 
Run the script, the programs tried to clicks few links, and that's it,. It does not do PC searching or Mobil Device Searching at all.

Anything that I am missing here?

Here is my logs:

2017-03-24 01:47:23.2 - script started
--------------------------------------------------------------------------------

Live - myemail@gmail.com
Result 1/18:
-----------
name        : Daily search
url         : http://www.bing.com/news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1
progressCur : 0
progressMax : 50
progress %  : 0.00%
description : Earn up to 50 points per day, 5 points per search.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Live - myemail@gmail.com

Points before:       505
Points after:        505
Points earned:         0
Lifetime Credits:    505

--------------------------------------------------------------------------------
Total points earned: 0

2017-03-24 01:47:27.6 - script ended

Process finished with exit code 0

**Comment by puternutt** [comment]
@frank777777777 Mine does that too, but directly after it ends the script, I immediately kick it off again and the searches begin. I run the script twice a day, typically back to back or as close as I can and I end up getting the daily's and the searches. Give that a shot and see what you end up with.

**Comment by frank777777777** [comment]
@puternutt  issue solved. You have to be Level 2 to be able to search using this script.
Also, my two other new accounts do not have Amazon GC redemption option, while my old account do.
Is it associated with the age of the account?

**Comment by adambird79** [comment]
Mine wasn't doing PC searches even on Level 2, I added the following to the accounts section:

<ua_desktop>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063</ua_desktop>

Now I get 6 points per search on PC searches.

**Comment by specu** [comment]
@adambird79 I just tried that string and i'm still geting 150 pc searches per day ("Earn up to 150 points per day, 5 points per search on PC."). I already had Edge 12 string set, so I'm getting 10 point extra daily activites. are you doing anything else to get 6 points per search?

**Comment by amayer5125** [comment]
Newest version has working searches
