### ISSUE TITLE
Searches not counting

### ISSUE THREAD

**Issue by uruloki** [sealemar/BingRewards#232]
I am currently running three accounts with the script. One of them is receiving all of the credit for searching, Two of them are not receiving any. All three are level 2 (previously Gold), and the logs show the searches going through. When I log into the account however, it has not registered the searches. The latest run from today is attached.

My setup is a cron job that calls a script to randomly select each of the three config files for the accounts.

I've pulled the latest main and made sure the Thursday fix was included.

[testing.txt](https://github.com/sealemar/BingRewards/files/900401/testing.txt)

**Comment by specu** [comment]
trying doing 1 day manually for each of those accounts. the following day it started working for me again.

**Comment by uruloki** [comment]
I'll give that a shot and report tomorrow.

**Comment by uruloki** [comment]
Doing the manual searches did not work, and now all three accounts are not recording searches.

**Comment by uruloki** [comment]
It took 2 days of manual searches. Maybe they need to see some kind of alternate activity on the account?
