### ISSUE TITLE
New 400 Error

### ISSUE THREAD

**Issue by martingehrke** [sealemar/BingRewards#238]
The server couldn't fulfill the request.
Error code:  400

**Comment by wastingoctober** [comment]
I'm seeing it as well. I tried completing all the quizzes manually and re-running, and I still got the same error.

**Comment by specu** [comment]
coffee break quiz does this . to fix in bingFlyoutParser.py you need to add a line after line 65:
        COFFEE_BREAK_QUIZ    = (16,   "Coffee break quiz",                 None, False, Action.PASS)
and then where it says ALL = (RE_EARN_CREDITS_PASS,
you have to add coffee break quiz to that array:
, SEARCH_AND_EARN, THURSDAY_BONUS, COFFEE_BREAK_QUIZ)

**Comment by wastingoctober** [comment]
@specu interesting. I had a completely different quiz, a lightspeed quiz, that caused the issue for me. Here's the line I added after 65, and my script ran through fine on all my accounts after that:

LIGHTSPEED_QUIZ       = (16,   "Lightspeed quiz",                    None, False, Action.PASS)

**Comment by specu** [comment]
thats a star wars may the 4th quiz - I didnt have a problem with that one

**Comment by ChiIIerr** [comment]
Have the same issue. Looking forward to an update soon for a fix!!

**Comment by waltr21** [comment]
Also getting error: 400, but I've run into an interesting problem. I tried to add LIGHTSPED_QUIZ and COFFE_BREAK_QUIZ into bingFlyoutParser.py, but I still get the error. I then tried to complete the quizzes by hand, but they won't check complete on the rewards web page. I complete the quiz, but when returned to the rewards webpage, I still have the option to take the quiz for X amount of points. This happens for every type of quiz available.

**Comment by wastingoctober** [comment]
@waltr21 I actually had to add one more line for the "Supersonic quiz" to my code for one of my accounts. So my final lines added are as follows:
`        LIGHTSPEED_QUIZ       = (16,   "Lightspeed quiz",                    None, False, Action.PASS)`
`        COFFEE_BREAK_QUIZ       = (17,   "Coffee break quiz",                    None, False, Action.PASS)`
`        SUPERSONIC_QUIZ       = (18,   "Supersonic quiz",                    None, False, Action.PASS)`

`        ALL = (RE_EARN_CREDITS_PASS, RE_EARN_CREDITS, SEARCH_MOBILE, SEARCH_PC, YOUR_GOAL, MAINTAIN_GOLD,`
`               REFER_A_FRIEND, SEND_A_TWEET, RE_EARNED_CREDITS, COMPLETED, SILVER_STATUS, INVITE_FRIENDS,`
`               EARN_MORE_CREDITS, SEARCH_AND_EARN, THURSDAY_BONUS, LIGHTSPEED_QUIZ, COFFEE_BREAK_QUIZ, SUPERSONIC_QUIZ) `

There should be a way we can make this more intelligent so it just looks for "QUIZ" and takes the appropriate action. I haven't had time to dig into the code enough to see this though. Judging by how explicit everything is currently, I'm assuming that the exact string must match as it's currently configured.

**Comment by martingehrke** [comment]
Yea this is extremely fragile. also you could easily make this a dict and
then get keys for ALL.

**Comment by puternutt** [comment]
@waltr21 

I've added the following and I get an error on the lightspeed quiz here is what I added: 

        COFFEE_BREAK_QUIZ    = (16,   "Coffee break quiz",                 None, False, Action.PASS)
		LIGHTSPEED_QUIZ      = (17,   "Lightspeed quiz",                   None, False, Action.PASS)
		SUPERSONIC_QUIZ      = (18,   "Supersonic quiz",                   None, False, Action.PASS)

        ALL = (RE_EARN_CREDITS_PASS, RE_EARN_CREDITS, SEARCH_MOBILE, SEARCH_PC, YOUR_GOAL, MAINTAIN_GOLD,
               REFER_A_FRIEND, SEND_A_TWEET, RE_EARNED_CREDITS, COMPLETED, SILVER_STATUS, INVITE_FRIENDS,
               EARN_MORE_CREDITS, SEARCH_AND_EARN, THURSDAY_BONUS, COFFEE_BREAK_QUIZ, LIGHTSPEED_QUIZ, SUPERSONIC_QUIZ)

but the error is as follows:

Progress counter : Traceback (most recent call last):
  File "C:\Users\%username%\OneDrive\BingRewards-master\main.py", line 24, in <module>
    from bingRewards import BingRewards
  File "C:\Users\%username%\OneDrive\BingRewards-master\pkg\bingRewards.py", line 18, in <module>
    import bingFlyoutParser as bfp
  File "C:\Users\%username%\OneDrive\BingRewards-master\pkg\bingFlyoutParser.py", line 67
    LIGHTSPEED_QUIZ      = (17,   "Lightspeed quiz",                   None, False, Action.PASS)
    ^
IndentationError: unexpected indent

**Comment by wastingoctober** [comment]
@puternutt You may want to check the formatting with the tabs. It's quite possible that my copy/paste messed things up. Just make sure everything aligns as it should with the rest of the code.

**Comment by FunkyEssence** [comment]
Here is the "bingFlyoutParser.py" file with the coffee break, lightspeed and supersonic quizes added. Just download and replace in your Bing Rewards/pkg folder.

https://www.dropbox.com/s/mkxne9kmudhaimp/bingFlyoutParser.py?dl=1

**Comment by specu** [comment]
if you have time, consider creating pull request for it. you can find instructions easly if you google.
I still get occasional 400 with that though. I wonder if it's for certain browser strings.

**Comment by puternutt** [comment]
Thanks @FunkyEssence I did a comparison of the files and updated mine to match exactly as the one you gave and I received the same error. I then renamed mine to .old and placed yours in and the script is running now. So there is something in yours that is not in mine that allows the updated lines

**Comment by puternutt** [comment]
Thought I would place this out there too

The error I get is this:

The system cannot find the path specified.
The system cannot find the path specified.

then it goes to pausing between accounts and moves on. Here is what the log says in errors and warnings just before those two pop up. See below. 

Result 1/10:
name        : Triple shot quiz
url         : https://www.bing.com/rewards/checkuser?ru=%2Fsearch%3Fq%3DBest+movies+2017%26raid%3Dquiz%26rnoreward%3D1%26FORM%3DML12JG%26rqw%3D1%26skipopalnative%3Dtrue%26rqpiodemo%3D1%26roid%3D10XMSRewards_MSR_ThursdayBonusQuiz_20170511&rabruid=0
progressCur : 0
progressMax : 50
progress %  : 0.00%
description : Time for a bonus quiz-answer all 5 questions correctly to earn 50 points!
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 7/10:
name        : Earn more points
url         : http://www.bing.com/rewardsapp/redirect?url=microsoft-edge%3ahttps%3a%2f%2faccount.microsoft.com%2frewards%2fdashboard%3fFORM%3dML1329&id=10XMSRewards_a24041748&hash=30956d3a78339baba74dea378c245e31&state=Completed&rcid=0&aid=urlreward&bruid=4D69E29C-87F8-4AA5-BA4F-0FBB1832FFC3&ml=ExpandedWebLayout&rh=
progressCur : 5
progressMax : 5
progress %  : 100.00%
description : Check your rewards page on Microsoft Edge for a bonus offer.
   Message  : This reward has been already achieved
   Action   : warn

Results 8/10:
name        : On a carousel
url         : http://www.bing.com/rewardsapp/redirect?url=%2fimages%2fsearch%3fq%3dHistoric%2520carousels%26FORM%3dML14VE%26OCID%3dML14VE%26wt.mc_id%3dML14VE%26rnoreward%3d1%26rnoreward%3d1&id=10XMSRewards_a24041716&hash=2f176ff4ca74300a977b61ff30ee7b22&state=Completed&rcid=0&aid=urlreward&bruid=4D69E29C-87F8-4AA5-BA4F-0FBB1832FFC3&ml=ExpandedWebLayout&rh=
progressCur : 10
progressMax : 10
progress %  : 100.00%
description : We've been going in circles for almost 400 years.
   Message  : This reward has been already achieved
   Action   : warn

**Comment by FunkyEssence** [comment]
@puternutt Not sure if this will help, but i updated the bingFlyoutParser to pass on triple shot quizes.

**Comment by specu** [comment]
pls test the pull request from request 239

**Comment by FunkyEssence** [comment]
@specu the occasional 404 may come from the doubleshot or tripleshot quizes. Not sure, just a thought. Also, I updated my flyoutparser file to pass on "YOUR_GOAL", "MAINTAIN_GOLD" and "EARN_MORE_CREDITS", as I dont think these are necessary to be informed about. Especially for the gold since that is no longer valid.

**Comment by wastingoctober** [comment]
Thanks for the quick repo patching, @amayer5125!

**Comment by puternutt** [comment]
@FunkyEssence What did you update in the bingFlyoutParser?

**Comment by wastingoctober** [comment]
@puternutt [Here's the changelog](https://github.com/sealemar/BingRewards/commit/30cbe054146d5dde8b28f23b2c4c1dd4474f0722).

**Comment by specu** [comment]
patch 100% by wastingoctober not me, despite what it says there.
whole pull request can be done in a browser, it's pretty easy.

**Comment by puternutt** [comment]
@wastingoctober @specu Thanks, I did however take a look at the log and @FunkyEssence provided earlier the file to save that had that information done in it already and the other errors went away, but the ones I posted still exist. What I was asking just a few minutes ago was in regards to this comment:

"FunkyEssence commented 3 hours ago
@puternutt Not sure if this will help, but i updated the bingFlyoutParser to pass on triple shot quizes"

**Comment by FunkyEssence** [comment]
@puternutt

I was just talking about passing another quiz (triple shot) since it was giving you a warning, but I dont think that would have changed anything. Here is my personal bingFlyoutParser... I added every quiz I could think of since I don't want to be notified about any of them. 

It passes:
- coffee break
- double shot
- triple shot
- thursday bonus
- supersonic
- lightspeed
- warp speed

Also, I selected pass instead of inform for the "YOUR_GOAL", "MAINTAIN_GOLD" and "EARN_MORE_CREDITS". By passing those, all my accounts now run on the first attempt, when before it would always throw me a 302 error on attempt one, then successfully complete attempt 2. That happened every time.

Here is the file if you wanted to try it:
https://www.dropbox.com/s/wryd93r26tyek6v/bingFlyoutParser.py?dl=1

**Comment by specu** [comment]
@puternutt I like this one a lot. if it could also trigger search for Silver level as well as inform what is being tried before it reports an error that would be awesome. Do you want to do a pull request of your version?

**Comment by baltimoron** [comment]
You can use a regex to capture all the quiz links. Add the following line after EARN_CREDITS_RE...:

QUIZ_RE = re.compile("\w*quiz\w*")

Then add the following to the rewards type enumerator thing:

ALL_QUIZ             = (16,   QUIZ_RE,                             None, True, Action.PASS)

and add ALL_QUIZ to the list.

**Comment by puternutt** [comment]
Thanks @FunkyEssence I've placed the file and the errors are gone so far and Thanks @baltimoron I've added those as well and again no errors as of yet. I have SMStrace running watching the log file in real-time and no errors as of yet. 

I've attached the file here for anyone that needs it, Just remove the .txt from the end once you download it. 

[bingFlyoutParser.pyc.txt](https://github.com/sealemar/BingRewards/files/1010812/bingFlyoutParser.pyc.txt)

**Comment by baltimoron** [comment]
Turns out I derped on the RE thing and you just need "quiz". The original also had a couple of *s in it after the \w but it looks like they were stripped out when I posted, not that it matters.

**Comment by wastingoctober** [comment]
@baltimoron I was wondering about that. So you don't need to make it ".*QUIZ.*" (it automatically wraps wildcards around it)? Very familiar with regex but not necessarily the Python specifics of it.

**Comment by puternutt** [comment]
@baltimoron So you should have the following?

         QUIZ_RE = re.compile("\quiz\wss") # removed w in front, added the SS at the end of the last w
		
#       Alias                   Index Reward.name
#                           optional(Reward.description)                         isRe?  Action

        blahblahblah        = (1 thru 21)                                   none etc etc
        ALL_QUIZ             = (22,   QUIZ_RE,                             None, True, Action.PASS)
		
        ALL = (blahblahblah.... , ALL_QUIZ)

**Comment by specu** [comment]
how about this (I tested it):
https://github.com/specu/BingRewards/raw/master/pkg/bingFlyoutParser.py

in addition this patch tells which reward is being tried before the script craps out (I did not test it yet, should be tested prior to applying above), so future reports wouldnt just report error 400 but also the name of the activity:
https://github.com/specu/BingRewards/raw/master/pkg/bingRewards.py

**Comment by baltimoron** [comment]
re.compile("quiz") 

works in this case, guess I just wasn't aware of exactly how regular expressions worked in python.

**Comment by puternutt** [comment]
@specu Thank you again the other day for adding the print option in the one file that prints the error location, I have two warns in my log, so here is the details:, These warn actions are causing a "The system cannot find the path specified." error

name        : They're back
url         : http://www.bing.com/rewardsapp/redirect?url=%2fsearch%3fq%3dAlien%253A%2520Covenant%2520cast%26FORM%3dML14VG%26OCID%3dML14VG%26wt.mc_id%3dML14VG%26rnoreward%3d1%26rnoreward%3d1&id=10XMSRewards_a24041718&hash=6e8a08ad7b2e9673fd1dd984fa4e474a&state=Completed&rcid=0&aid=urlreward&bruid=1155C7AE-B831-4203-8FE6-616D0BF3A0E1&ml=ExpandedWebLayout&rh=
progressCur : 10
progressMax : 10
progress %  : 100.00%
description : The Alien saga continues with Ridley Scott's latest, opening today.
   Message  : This reward has been already achieved
   Action   : warn (this is highlighted as a warning)
----------------------------------------
name        : Earn more points
url         : http://www.bing.com/rewardsapp/redirect?url=microsoft-edge%3ahttps%3a%2f%2faccount.microsoft.com%2frewards%2fdashboard%3fFORM%3dML1329&id=10XMSRewards_a24041750&hash=563c4f79930e46c188e58b4ae305d849&state=Completed&rcid=0&aid=urlreward&bruid=1155C7AE-B831-4203-8FE6-616D0BF3A0E1&ml=ExpandedWebLayout&rh=
progressCur : 5
progressMax : 5
progress %  : 100.00%
description : Check your rewards page on Microsoft Edge for a bonus offer.
   Message  : This reward has been already achieved
   Action   : warn  (this is highlighted as a warning)
---------------------------------------
Processing WARN: 'They're back' (this is highlighted as a warning)
Processing WARN: 'Earn more points' (this is highlighted as a warning)
Processing SEARCH: 'PC search'
Processing SEARCH: 'Mobile search'

**Comment by amayer5125** [comment]
Should this issue be reopened until we get a pull request together?

**Comment by specu** [comment]
I thought I had a pull request in and i kind of though it was merged in?

**Comment by amayer5125** [comment]
It did work. But now mine are failing again. And it seems like there are more quizzes that need address.

**Comment by specu** [comment]
@amayer5125 if you've applied my verbosity patch, which activity is giving you 400 now? I'm not getting any errors but I took someone's advice and marked additional activities to skip instead of warn (3 of them, I can look it up).

**Comment by jbrobst** [comment]
@amayer5125 Have you tried #244?

**Comment by FunkyEssence** [comment]
@amayer5125 I added pull request #244 to pass all quizzes. This works with all current quizzes and should also work with any future quizzes as well (that include the word "quiz"). Test it out.
