### ISSUE TITLE
The server couldn't fulfill the request. Error code:  400

### ISSUE THREAD

**Issue by FadeVT** [sealemar/BingRewards#240]
The server couldn't fulfill the request.
Error code:  400

Starting a couple of days ago, I started seeing this error on all but two of the accounts. 

As of today, every account I have returns this error. 

Everything seems OK on Bings end. (No issues logging in or anything.) 

Last pull was 5 minutes before posting this.

**Comment by martingehrke** [comment]
I got this a couple of days ago, there was a fix, and it is back. This has to do with how it handles the new quizes that keep popping up. I think there is a regex fix that might work. I am going to give it a shot

**Comment by DarkAlexWang** [comment]
I have the same error even after pulled the new fix.

**Comment by specu** [comment]
there's discussion on it issue #238

**Comment by ChiIIerr** [comment]
Can someone explain how to fix this? I read through the other thread but didn't see the solution. Thanks!

**Comment by martingehrke** [comment]
If you've done a recent update, please provide run with --verbose and provide details and output.

**Comment by FunkyEssence** [comment]
@ChiIIerr Try this. Replace your current 'bingFlyoutParser.py' file in the 'pkg' folder with the one below.

https://www.dropbox.com/s/wryd93r26tyek6v/bingFlyoutParser.py?dl=1

**Comment by ChiIIerr** [comment]
Thank you!!! That worked :D

**Comment by FadeVT** [comment]
Funky, thank you very much! This solved my issue as well!

**Comment by Brenex** [comment]
Thanks, fixed it for me too

**Comment by codingqt** [comment]
Thank you @FunkyEssence !

**Comment by wipedout** [comment]
I barely know how so spell python, let alone review the code and confirm that it is legitimate and effective. Any chance the updated file will be put into an update with a new version for those of us less skilled in the art? Many thanks!

**Comment by FunkyEssence** [comment]
I added the exact change in the file above to pull request #244. This was created 10 days ago on May 18th, but has yet to be added.

I just added the link above for people who wanted to get the bot back up and running while the pull request is pending.
