### ISSUE TITLE
Edge Bonus Quiz not being handled

### ISSUE THREAD

**Issue by AnthonyBe** [sealemar/BingRewards#245]
I just noticed a new quiz, **Edge Bonus Quiz**, that the latest Git version (1st June) of the script is not handling.
I saw the quiz, ran the scripts (having already run them a few hours earlier) and no new points were earned.
I then went back to the Rewards page and the quiz was still available and I was able to complete and earn points from it.

**Comment by specu** [comment]
The script doesnt handle any quizzes

**Comment by AnthonyBe** [comment]
Ah. That would explain it then! :)

**Comment by AnthonyBe** [comment]
Could it handle quizzes? :)

**Comment by amayer5125** [comment]
@AnthonyBe yes the script could handle quizzes. We just havent had anyone step up and write a pull request yet. Realistically though I doubt its worth the time to write code to do a quiz that is a one time thing.

**Comment by DimaRazb** [comment]
Hey, guys!
The script collects Edge bonus quiz and basic browser 10 points quiz pretty fine, but PC and mobile searches doesn't work for about 4 days for my 2 accounts. Changed nothing, I've just run the script as always before this bad thing happened.
 Any insights?
