### ISSUE TITLE
Neither PC nor mobile searches counted

### ISSUE THREAD

**Issue by sensboston** [sealemar/BingRewards#247]
Today (07/27/17) neither PC nor mobile searches counted :( Manual searching however works fine. It looks like MS changed something yesterday evening.

Could you please take a look and confirm (and fix if possible)?

Thanks a lot!

**Comment by adambird79** [comment]
Working for me I can see my points going up as I watch the script go through.

Though I have had issues before with running the script on Linux if I have hard coded the user agent to edge.

**Comment by sensboston** [comment]
Oh, thanks! Changed to "Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0" and searches started counting again. Fake alarm :) 

Could you please provide your user agent strings (for mobile too)? Thanks!

**Comment by sensboston** [comment]
BTW, mobile searches still not counting :(

**Comment by amayer5125** [comment]
This should be fixed with the newest release.
