### ISSUE TITLE
Python or script not working?

### ISSUE THREAD

**Issue by TechNGamer** [sealemar/BingRewards#248]
I don't know if this is just python being a bitch or if it's the script but I keep getting this error when I try and run the script;
```python
  File "main.py", line 64
    print "-" * 80
            ^
SyntaxError: Missing parentheses in call to 'print'
```
When I learned python I was told that every time you call print you must do it as so
```python
print("Hello World")
```

**Comment by jbrobst** [comment]
The script only works with python 2.7. Before python 3 there was a print statement that had its own syntax, but in python 3 it was made a function ([here's why](https://www.python.org/dev/peps/pep-3105/)).

**Comment by TechNGamer** [comment]
@jbrobst Well that's kinda weird. Someone who can should probably change the README.md requirements to say something along the lines of "Python 2.7 to (the version before 3.0)" instead of it saying, "Python 2.7+". Saying, "Python 2.7+" make it seems like it works on any version of python 2.7 or higher. I personally don't care about python so I knew none of this. Do you think the guys working on this program should upgrade it to python 3.0 or no?

**Comment by blakekl** [comment]
Python 3 is a significant change from python 2. Many people actually have both installed and you can run the desired version (python command for 3.x and python2. It's not a few simple changes to convert something to python 3 from python 2. It's a rewrite. This issue should be closed.

**Comment by amayer5125** [comment]
For now we will stick with python 2. After major platforms start shipping with python 3 installed (looking at you Mac OS) we may convert to python 3.
