### ISSUE TITLE
I need help setting up...

### ISSUE THREAD

**Issue by enzo-code** [sealemar/BingRewards#249]
How do I sign up to MS Rewards with a facebook account? I already have an MS account, which had 3,000 points when I found out about this. Can I link my facebook account to MS Rewards?

**Comment by enzo-code** [comment]
Is Facebook login even supported? How else do I login?

**Comment by enzo-code** [comment]
I don't see an area to put my MS credentials.

**Comment by amayer5125** [comment]
Facebook login is not supported by Bing Rewards anymore.

Did you read the [README](https://github.com/sealemar/BingRewards#running-the-script). It tells you where to put your MS creds.

**Comment by enzo-code** [comment]
<accounts>
        <account type="Live" disabled="false">
            <login>gogo@hotmail.com</login>
            <password>xxx</password>
        </account>
        <account type="Live" disabled="false">
            <login>hoho@hotmail.com</login>
            <password>xxx</password>
        </account>
    </accounts>

this part?

**Comment by amayer5125** [comment]
Yup. Just fill in one as many accounts as you have and delete the rest of the examples.

If you need more info on accounts it can be found [here](https://github.com/sealemar/BingRewards#accounts).

If this answers all of your questions please close this issue.

**Comment by enzo-code** [comment]
I get ConfigError: Corresponding account is not found for EVENTS.ACCOUNT.ref = [(email)]

**Comment by amayer5125** [comment]
If you arent using any of the events just remove them.  
Should look like:
```xml
<events>
</events>
```

**Comment by enzo-code** [comment]
`No RegEx matches found for this search and earn
Result 1/2:
-----------
name        : Search and earn
url         : http://www.bing.com/explore/rewards?FORM=MA1377&wt.mc_id=MA1377
description : For a limited time you're earning free credits. Activate your account to claim them.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search

Result 2/2:
-----------
name        : Join Now
url         : http://www.bing.com/explore/rewards?FORM=MA1377&wt.mc_id=MA1377&PUBL=BINGCOM&CREA=MA1377
description : Use Bing. Join Bing Rewards to start earning credits toward free rewards.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn
`

i get this error

**Comment by specu** [comment]
sounds like you need to activate your account?

**Comment by enzo-code** [comment]
My account is activated... with 3,000 points

**Comment by specu** [comment]
that's odd, are you seeing those activities when you log via PC?

**Comment by enzo-code** [comment]
I dont believe so... i entered my two emails in the accounts section, and i completely deleted the events section.

**Comment by enzo-code** [comment]
i'm able earn rewards manually. may you please tell me the steps you took
to set up your account?

**Comment by specu** [comment]
I simply followed instructions provided. I've never seen those errors so i'm not sure how to fix them.

**Comment by enzo-code** [comment]
GNU nano 2.7.4                                                          File: config.xml                                                                    



    Note: login and password are optional

        if not set, the proxy is considered open

        only Basic HTTP Authentication is currently supported

        protocols: a comma separated list of values - i.e, "http,https"

    <proxy protocols="http,https" url="218.204.159.45:8123" login="John Smith" password="xxx" />

    -->



    

    <accounts>

        <account type="Live" disabled="false">

            <login>sailormanenzo@gmail.com</login>

            <password>***</password>

        </account>

        <account type="Live" disabled="false">

            <login>sailormanenzo@outlook.com</login>

            <password>***</password>

        </account>

    </accounts>



    

    <queries generator="wikipedia" />

</configuration>



I have purposely blotted out the password. I have completely deleted everything from <events> to </events>
