### ISSUE TITLE
As of today (8/20/2017), the script is not working.

### ISSUE THREAD

**Issue by abhidotnet** [sealemar/BingRewards#250]
Bing has changed somethings on their end. This is the message on the script.

```
name        : PC search
url         : http://www.bing.com/news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1
progressCur : 130
progressMax : 300
progress %  : 43.33%
description : Through 8/31, earn 2x the usual! Up to 300 points per day, 5 points per search.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search
```

**Comment by specu** [comment]
that's pretty awesome, i'll create a regex shortly

**Comment by specu** [comment]
in pkg/bingFlyoutParser.py for now I changed the line that has SEARCH_AND_EARN_DESCR_RE to say:
        SEARCH_AND_EARN_DESCR_RE = re.compile(r".*p to (\d+) points? (?:per day|today), (\d+) points? per search.?")

I'm dont know python, so I dont know if the match is supposed to be partial (to match preceeding promo text) or case insensitive ("Up to" vs "up to"), but it's just the promo description throws off the code that determines search count that needs to be performed.

**Comment by abhidotnet** [comment]
The good news is that the script is not failing. I am not sure about the points earning part since I already did manual searches and earned the points for today.

**Comment by wipedout** [comment]
For those who don't speak python, modify the existing "SEARCH_AND_EARN_DESCR_RE" line with the modified syntax; do not try to comment out the original and add a new line. You'll get a script error (IndentationError: unexpected indent).

Once again, Thank You to the skilled and wise folks who figure this out *and* share it!

**Comment by xcalvinsz** [comment]
Thanks specu and wipedout, i commented out the original and was wondering why it didn't work.

**Comment by abhidotnet** [comment]
Commenting out the original will work, provided you have the correct number of spaces. This depends on the editor you use. On windows, I used Notepad++ to make this change.

If the editor being used replaces the spaces with TABS, then you're going to get the error that @wipedout refers to.

**Comment by kayla210** [comment]
I got a similar message when I first started running this. I ran it again and I haven't seen the message since, but still having other issues.

```
2017-08-20 16:14:58.9 - script started
--------------------------------------------------------------------------------

Live - ****
No RegEx matches found for this search and earn
Result 1/20:
-----------
name        : Search and earn
url         : http://www.bing.com/rewardsapp/redirect?url=%2fnews%2fsearch%3fq%3dTopStories%26FORM%3dML14AF%26wt.mc_id%3dML14AF%26rnoreward%3d1&id=10XMSRewards_LC_a0401170&hash=d3887c1077a7a53686f55d276c18ca79&state=Active&rcid=0&aid=urlreward&bruid=1712B89B-58B1-4BF4-80EB-BD3A88BA3328&ml=ExpandedWebLayout&rh=
progressCur : 0
progressMax : 5
progress %  : 0.00%
description : Earn a free sweepstakes entry when you make your first 3 Bing searches.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search

```

**Comment by specu** [comment]
@kayla210 I dont think the script works for level 1 membership, you have to get to level 2 manually, which takes less than a day.

**Comment by kayla210** [comment]
@specu I'll work towards that, thanks so much!

**Comment by abhidotnet** [comment]
This is now working. I will close.

**Comment by puternutt** [comment]
Just a curious comment here, I made the changes to the script as well indicated above, but I noticed the old code stated 

SEARCH_AND_EARN_DESCR_RE = re.compile(r"**Earn up to** (\d+) points? (?:per day|today), (\d+) points? per search.?")

New Code:

SEARCH_AND_EARN_DESCR_RE = re.compile(r"**.*p to** (\d+) points? (?:per day|today), (\d+) points? per search.?")

What is the **Earn up to** do and do we need to keep it?

**Comment by specu** [comment]
The number of searches that needs to be performed is read from that string which is the comment of the activity. The comment to PC Search activity currently doesnt say "Earn up to" anymore ("Through 8/31, earn 2x the usual! Up to 300 points per day, 5 points per search.") resulting in no match and an error. This is not an elegant solution (since I dont know python), but it works and can be reverted after 8/31. I dont think original had a "." after "search" either.

**Comment by puternutt** [comment]
no it it didn't have the "." in it, as I indicated above the original was the first line untouched since I downloaded the script from a year ago or so. I don't change anything until I see someone like you or someone else that makes a change and shows results, I then make a copy of the file and make the change and run it. if it results the same way then I leave it. if not I delete the file and bring the original back in play.

**Comment by specu** [comment]
I'm saying your "old code" line has a trailing .? which the repository doesnt, odd but doesnt really matter.
The text will probably be reverted back to "Earn up to" on 9/1. I'll leave it up to senior developers whether to make that change or not. Original script will probably work on 9/1 again but it might be the case that a similar promo is going to come along in future and my version would be more likely to accommodate it. It's not pretty (reason in second paragraph of my patch) but it works and it probably will be a bit better than original.
