### ISSUE TITLE
Same issue as #217 for current 2x points promotion...

### ISSUE THREAD

**Issue by GeistNet** [sealemar/BingRewards#251]
Is anyone else having the same issue as #217 for the current 2x points promotion through 8/31?  I get the error below when I run the script.  Anyone able to provide a fix??

Thanks.

----------------------------------------------------------------------
 No RegEx matches found for this search and earn
Result 1/18:
-----------
name        : Mobile search
url         : http://www.bing.com/explore/rewards-mobile?FORM=ML10NS&CREA=ML10NS&wt.mc_id=ML10NS&rnoreward=1
progressCur : 0
progressMax : 200
progress %  : 0.00%
description : Through 8/31, earn 2x the usual! Up to 200 points per day, 5 points per search.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search

**Comment by specu** [comment]
see #250

**Comment by GeistNet** [comment]
Thanks and fix...  My apologies for the double post.  My filter was set to only show open tickets and #250 was closed!
