### ISSUE TITLE
RegEx not working

### ISSUE THREAD

**Issue by uruloki** [sealemar/BingRewards#252]
The 2x points seems to be breaking the parser this month:

```
No RegEx matches found for this search and earn
No RegEx matches found for this search and earn
Result 1/16:
-----------
name        : PC search
url         : http://www.bing.com/news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1
progressCur : 0
progressMax : 300
progress %  : 0.00%
description : Through 8/31, earn 2x the usual! Up to 300 points per day, 5 points per search.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search

Result 2/16:
-----------
name        : Mobile search
url         : http://www.bing.com/explore/rewards-mobile?FORM=ML10NS&CREA=ML10NS&wt.mc_id=ML10NS&rnoreward=1
progressCur : 0
progressMax : 200
progress %  : 0.00%
description : Through 8/31, earn 2x the usual! Up to 200 points per day, 5 points per search.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search
```

I tried updating bingFlyoutParser.py line 44 to the following, but I got the same message:

    SEARCH_AND_EARN_DESCR_RE = re.compile(r"Through 8/31, earn 2x the usual! Earn up to (\d+) points? (?:per day|today), (\d+) points? per search")

I don't think it should matter because the RegEx should still match on the second half of the string, but was anyone else run into this?

**Comment by DaFees** [comment]
I was just about open my issue reporting this same error. I haven't tried anything as I don't have much of an idea as to what I am doing so I'm hoping someone else can come up with a solution!

**Comment by specu** [comment]
#250

**Comment by uruloki** [comment]
Thanks, I did the regex wrong.
