### ISSUE TITLE
RegEx match not found when 2x points offered

### ISSUE THREAD

**Issue by blakekl** [sealemar/BingRewards#253]
The RegEx is failing to find the points allowed for the day when the message changes, like right now for the double points offer.

**Comment by elisiano** [comment]
They have been discussing this in #250 but personally I'd like to see your PR (#254) merged so that newcomers always pull in the "right" code.

**Comment by blakekl** [comment]
I agree with you. And closing issues that have a solution to the problem without the solution being in the code base is pretty lousy. I mean, I went and did all the work of creating the PR thinking there was no solution yet.

**Comment by specu** [comment]
@blakekl I like your regex, if it was tested then it should be committed. @amayer5125

**Comment by blakekl** [comment]
I'm running it right now, and it's working.

```
➜ python2 BingRewards/main.py

2017-08-24 09:04:39.7 - script started
--------------------------------------------------------------------------------

Live - xxxxxxxxxxx@xxxxxx.xxx

Running PC searches

2017-08-24 09:04:44.6 -  1/63 - Search: white house```

**Comment by specu** [comment]
just a thought, but perhaps instead of [uU] there's a switch (and it makes sense to add it) to make this regex case insensitive?

**Comment by blakekl** [comment]
Link to show the regex working:

http://rubular.com/r/s3bTQusDI0

@specu It could have the regex case insensitive flag set, sure. I'm a little more cautious to use it since that is sort of a global change on the whole regex. It would work in this case though. The [uU] is better performance wise.

**Comment by blakekl** [comment]
Closing this issue since PR(#254) fixed this issue.
