### ISSUE TITLE
No RegEx Matches + another error

### ISSUE THREAD

**Issue by enzo-code** [sealemar/BingRewards#255]
I get this error:
```

2017-08-24 23:02:10.8 - script started
--------------------------------------------------------------------------------

Live - sailormanenzo@gmail.com
No RegEx matches found for this search and earn
Result 1/2:
-----------
name        : Search and earn
url         : http://www.bing.com/explore/rewards?FORM=MA1377&wt.mc_id=MA1377
description : For a limited time you're earning free credits. Activate your account to claim them.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search

Result 2/2:
-----------
name        : Join Now
url         : http://www.bing.com/explore/rewards?FORM=MA1377&wt.mc_id=MA1377&PUBL=BINGCOM&CREA=MA1377
description : Use Bing. Join Bing Rewards to start earning credits toward free rewards.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn


For: Live - sailormanenzo@gmail.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "./main.py", line 304, in <module>
    EventsProcessor.onScriptFailure(config, e)
  File "./main.py", line 302, in <module>
    __run(config)
  File "./main.py", line 227, in __run
    reportItem = __processAccountUserAgent(config, account, bingCommon.USER_AGENTS_PC, doSleep)
  File "./main.py", line 214, in __processAccountUserAgent
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "./main.py", line 183, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "./main.py", line 70, in earnRewards
    reportItem.lifetimeCredits = bingRewards.getLifetimeCredits()
  File "./pkg/bingRewards.py", line 131, in getLifetimeCredits
    s = page.index("NAP")
ValueError: substring not found

```

Here is my code:

```

Note: login and password are optional

    if not set, the proxy is considered open

    only Basic HTTP Authentication is currently supported

    protocols: a comma separated list of values - i.e, "http,https"

<proxy protocols="http,https" url="218.204.159.45:8123" login="John Smith" password="xxx" />

-->



<!--

See config options in the Accounts section of README

or view them here: https://github.com/sealemar/BingRewards#accounts

-->

<accounts>

    <account type="Live" disabled="false">

        <login>sailormanenzo@gmail.com</login>

        <password>***</password>

    </account>

    <account type="Live" disabled="false">

        <login>sailormanenzo@outlook.com</login>

        <password>***</password>

    </account>

</accounts>



<!--

generator="MODULE" must be a module in pkg/queryGenerators

current modules:

    bing - uses today's bing news page. Generates terms which may be partial words.

    wikipedia - uses today's wikipedia. Generates terms with whole words.

    googleTrends - uses today's google trends, and google suggested searches. This generator

                   generates whole words, generally consistent with a search syntax.  These terms

                   are anything trending and can be NSFW or terms for illegal items.

-->

<queries generator="wikipedia" />

```

I have purposely blotted out the password. I have completely deleted everything from 
```<events>```
to
  ```</events>```

**Comment by specu** [comment]
Why is gmail in there?

**Comment by enzo-code** [comment]
Thats my email I use with MS Rewards

**Comment by specu** [comment]
Try deleting that section

**Comment by enzo-code** [comment]
The "@gmail.com"? How will it know between both emails then?

**Comment by specu** [comment]
I got no idea how you're logging into microsoft with gmail in the first place. I've never seen those errors either.

**Comment by jbrobst** [comment]
Are you sure those are level 2 microsoft rewards accounts? What happens when you log in and go to [this page](https://account.microsoft.com/rewards/dashboard)?

**Comment by blakekl** [comment]
Looks like your account hasn't been activated yet, from the search and earn message. I've never seen those messages before.

**Comment by enzo-code** [comment]
I sign into my gmail as usual, I have 655 points in that account. Level 2

**Comment by specu** [comment]
have you tried getting rid of gmail section on your config file?

**Comment by blakekl** [comment]
The gmail section isn't the problem. I do the same thing and it works for me.

**Comment by enzo-code** [comment]
I have removed the gmail.com part. same stuff.

**Comment by enzo-code** [comment]
could my account be banned?

**Comment by blakekl** [comment]
not if you can still login manually.

**Comment by enzo-code** [comment]
ok

**Comment by enzo-code** [comment]
I think i figured it out. I get an email from microsoft saying Unusual Sign In activity.

"To help keep you safe, we required an extra security challenge."

Maybe its blocking the bot

**Comment by elisiano** [comment]
Usually you get that if you login from a new location. Once you verified that (in your account), it should be fine.
That said, so far I was unable to make the script earn points when run from a VPS, it needs to be on a residential line (I believe Microsoft blacklists some IPs but it's just speculation, I have no proof).

**Comment by enzo-code** [comment]
I am using a VPS. How can I verify it?

**Comment by blakekl** [comment]
Currently, there isn't an easy way to beat the extra security challenge from a VPS, unless you can access it with a desktop GUI, open a browser, and complete the challenge manually. If you can't do this, don't run it on a VPS.

**Comment by elisiano** [comment]
...or a proxy on the VPS (configured in your browser), I guess

**Comment by blakekl** [comment]
@elisiano That would also work, but is still more complicated than I want to explain on github comments. :)

**Comment by enzo-code** [comment]
Live - sailormanenzo@gmail.com
No RegEx matches found for this search and earn
No RegEx matches found for this search and earn
Result 1/19:
-----------
name        : PC search
url         : http://www.bing.com/news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1
progressCur : 0
progressMax : 300
progress %  : 0.00%
description : Through 8/31, earn 2x the usual! Up to 300 points per day, 5 points per search.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search

Result 2/19:
-----------
name        : Mobile search
url         : http://www.bing.com/explore/rewards-mobile?FORM=ML10NS&CREA=ML10NS&wt.mc_id=ML10NS&rnoreward=1
progressCur : 0
progressMax : 200
progress %  : 0.00%
description : Through 8/31, earn 2x the usual! Up to 200 points per day, 5 points per search.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search


Live - sailormanenzo@gmail.com

Points before:       665
Points after:        675
Points earned:        10
Lifetime Credits:    675

**Comment by enzo-code** [comment]
I figured out some of it. I know get this error.

**Comment by blakekl** [comment]
This is due to a bug that I fixed in a pull request a few days ago PR(#254). Update your code.

**Comment by enzo-code** [comment]
all i have to do is clone it again?

**Comment by blakekl** [comment]
If you haven't made any changes to the code, then run this:

`git checkout master && git pull`

This will update your code to the latest. I have the git pull command run in my cron job so that I always have the latest code.

**Comment by enzo-code** [comment]
Okay. So I have it working on one email, but not my outlook one. It runs through the gmail perfectly, but stops after that. I comment out the gmail login, only running the outlook and i get this error:

is there a setting that i must do to allow me to use 2 emails?

**Comment by jbrobst** [comment]
That's an xml syntax error - make sure your config.xml has all the tags closed properly.

**Comment by enzo-code** [comment]
how would I know if the tags are closed.

**Comment by blakekl** [comment]
http://bfy.tw/DeQ5

**Comment by enzo-code** [comment]
Thank you all, my script is working fine.

**Comment by puternutt** [comment]
@blakekl  I noticed you stated "git checkout master && git pull" and that you run a cronjob for it? 

I'm running Python on a PC, how would I do it on it? would it be 

C:\python git checkout master && git pull

Or what?

**Comment by blakekl** [comment]
Git is a completely separate program from python. look around for tutorials and such if you want to know how to use it, but it's the program devs use to manage their source code changes. It's too much for me to explain when there are already so many resources out there.

**Comment by puternutt** [comment]
@blakekl  that's fine, that's all I needed to know, I can figure out the rest if there is anything I can do on my end to accomplish that task. Thank you for your time.

**Comment by jbrobst** [comment]
@enzo-code I should have elaborated; I just meant that every <tag> needs the corresponding </tag> and it all has to be nested such that tags are closed before their parent tag - glad you got it working!

@puternutt Download [git for windows](https://git-scm.com/downloads) and create a task which runs

    "C:\Path\To\git.exe" -C "C:\Path\To\BingRewards" pull

Replace the paths with wherever you have git.exe and the BingRewards directory. And of course you can just write `git` instead of the full path to git.exe if the directory for git.exe is in your PATH environment variable; I think the git for windows setup will do that for you. Also make sure your BingRewards directory has a .git directory in it. If you've just downloaded the zip of the repository it won't have it, instead you'll have to run

    git clone https://github.com/sealemar/BingRewards.git "C:\Path\For\BingRewards"

from a command prompt and copy over your config.xml. If you want to know more about git I'd definitely recommend reading a few chapters of [this book](https://git-scm.com/book/en/v2).
