### ISSUE TITLE
Daily Quiz's not completing

### ISSUE THREAD

**Issue by ndbills** [sealemar/BingRewards#256]
(First post on here, go easy :) )
Is anyone else not getting the daily quiz's (any of the quiz's)? It seems that I am not getting the quiz's since the 2x search points change. I've been following the threads for the regex updates and have updated my bingFlyoutParser.py with the new regex for the "search and earn description", and the searches for PC and mobile are working great. But the quiz's don't seem to get hit. I've tested this out in my Linux and Windows environments, but was wondering if anyone else is having issues with that.

Thanks in advance,

**Comment by specu** [comment]
the script doesnt do quizzes

**Comment by kenneyhe** [comment]
There are few bugs on bing reward side. i.e.: their webpage hide an quiz but the code shows it exists. I doubt it will be automated as iMacro can not even record the mouse movement yet.. see (below). any one got any macro tools that will do it? PM me. 

https://cl.ly/2N3F2P00362g

**Comment by amayer5125** [comment]
This script does not support quizzes.
