### ISSUE TITLE
Google Cloud Engine 

### ISSUE THREAD

**Issue by Shah-Parth** [sealemar/BingRewards#258]
This is more of a question than a bug or an issue.

I have been trying to make this work with Google cloud engine micro instance which is free, this way I don't have to worry about keeping my internet up all the time and a device on 24x7.

The issue I run into is that when the script runs, the points don't get counted. Anyone know why? I assume that it is because Microsoft has blocked the Google IP.

So yeah... anyone knows a solution to this where I don't end up running the computer 24x7 at home?

**Comment by blakekl** [comment]
It could be that the google iOS are locked. It could also be that there is added security checks due to login from an unrecognized IP. Have you checked your email to see if there is a security challenge notification?

**Comment by Shah-Parth** [comment]
There isn't a security challenge notification, I have double checked that. Log says it is done doing the search after logging in, but the points aren't counted towards the total.

**Comment by blakekl** [comment]
The searches ont always count. Are you doing retries? Mine will retry up to 10 times.

**Comment by Shah-Parth** [comment]
yep. It re-tries 3 times every single time it is successful with searches yet the points aren't counted.

**Comment by blakekl** [comment]
Yeah, that definitely does happen. Which is why I have mine set to 10. Not sure why the points don't get counted. Sometimes it helps for me to log in and manually complete the quizzes.

**Comment by amayer5125** [comment]
This could be specific to Google Cloud. We know bing.com blocks IPs of some cloud hosting providers. Since the script in general accrues points, I believe this is a google cloud specific issue which we have no control over.
