### ISSUE TITLE
Not earning any points for searches

### ISSUE THREAD

**Issue by phoenix87ta** [sealemar/BingRewards#260]
Using the latest version, I'm not getting any points for searches.  Verbose output shows the following:

Result 13/15:
-----------
name        : Daily search
url         : http://www.bing.com/news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1
progressCur : 0
progressMax : 50
progress %  : 0.00%
description : Earn up to 50 points per day, 5 points per search.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Same result with and without manually configured user agents strings, and everything else seems to work okay, but searches don't earn any points and don't seem to throw any meaningful errors.

**Comment by specu** [comment]
You need to get to level 2 manually.

**Comment by phoenix87ta** [comment]
Ah, well that would explain it.  Is that in the doc and I missed it?

**Comment by duddles** [comment]
I'm also not getting any points today but am at level 2 - any other ideas to try?

**Comment by specu** [comment]
@duddles run it manually for a day or 2

**Comment by zengfu94** [comment]
@duddles It seems to be a real issue 90% of my accounts are not earning.

**Comment by DARKKRAKEN** [comment]
Getting the same issue.

**Comment by kenneyhe** [comment]
I wrote a private docker container to handle level 1 long ago if people want to try it and give me a star. 👍 PM for help/to contribute.  But the github repo is https://github.com/kenneyhe/mobile .  see dockerfile and obviously replace with your credentials... :)

**Comment by Mailman74** [comment]
My accounts are not earning neither. I can see they logged in on activity page and they are searching but searches are not counting.

**Comment by DARKKRAKEN** [comment]
Check the other thread about authorisation error for a solution.

**Comment by amayer5125** [comment]
Moved to #262
