### ISSUE TITLE
"Could not find variable WindowsLiveId on login page"

### ISSUE THREAD

**Issue by RewardsMaster** [sealemar/BingRewards#270]
Started happening today. An authentication error. Errors. Retries. Hangs the script.

**Comment by amayer5125** [comment]
This is fixed in the newest version.

**Comment by RewardsMaster** [comment]
Unfortunately this is not true. I am using the latest version.

**Comment by lukedukeus** [comment]
I still have this issue with most recent revision

**Comment by lukedukeus** [comment]
--------------------------------------------------------------------------------
The system cannot find the path specified.
AuthenticationError:
Could not find variable 'WindowsLiveId' on Live login page

**Comment by specu** [comment]
@lukedukeus please try deleting *.pyc files

**Comment by specu** [comment]
@RewardsMaster please try deleting *.pyc files
