### ISSUE TITLE
New Error today

### ISSUE THREAD

**Issue by NotDillbert** [sealemar/BingRewards#276]
The script ran early this morning, but did not amass all the points I typically get.  When I ran the script manually I received the following error:

Live - xxxxxxxxx@gmail.com
Result 1/16:
-----------
name        : Xbox Live Gold
url         : http://www.bing.com/rewardsapp/redirect?url=http#############
description : Prep for Xbox One X: Use points to join or re-up your membership now.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

When I went to the web site and used the "Xbox Live Gold" link and reran the script I received this error:

   Live - xxxxxxxxx@gmail.com
The server couldn't fulfill the request.
Error code:  302

For: Live - xxxxxxxxx@gmail.com

Thoughts?

**Comment by specu** [comment]
my script didnt crap out on this one.
please always hash out bruid when you post logs publicly.

**Comment by kenneyhe** [comment]
No error running on edge user agent for me

**Comment by NotDillbert** [comment]
Pardon me for being a novice, but what is a  bruid?

Also the code from Kenney help, but I am still getting the following error:
The server couldn't fulfill the request.
Error code:  302

**Comment by kenneyhe** [comment]
The error might be your UA string

**Comment by NotDillbert** [comment]
It is working today.  Thanks everyone.
