### ISSUE TITLE
ua_mobile iPhone is not working

### ISSUE THREAD

**Issue by kenneyhe** [sealemar/BingRewards#278]
```python
<ua_mobile>mozilla/5.0 (iphone; cpu iphone os 7_0_2 like mac os x) applewebkit/537.51.1 (khtml, like gecko) version/7.0 mobile/11a501 safari/9537.53</ua_mobile>
```

Above is failing and removal of it fixes it. Microsoft Reward might be obsoleting older iOS version...

**Comment by zengfu94** [comment]
Tags are wrong, read the README. User agent is also out of wack, this is not an error in the bot.

**Comment by kenneyhe** [comment]
Ok

**Comment by kenneyhe** [comment]
@zengfu94 if that is true, my ua_desktop will not be using edge browser and should not accrue PC Search points. So there is still some problem with that explanation...

<ua_desktop>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136</ua_desktop>

**Comment by amayer5125** [comment]
If the above user agent does not work why don't you just try using a newer one?

**Comment by kenneyhe** [comment]
I removed the ua_mobile and it works, like I said. It better without that option for the people who has similar trouble.
