### ISSUE TITLE
No Searching, Empty Log

### ISSUE THREAD

**Issue by fraser1974** [sealemar/BingRewards#282]
Yesterday and today I've been getting this on one of my accounts:
2017-10-07 13:04:09.4 - script started
--------------------------------------------------------------------------------

Live - ***@hotmail.com

For: Live - ***@hotmail.com

--------------------------------------------------------------------------------

Full log:
---------
Empty log
onScriptFailure: -mail

And on the rest of my accounts, something slightly different happens, but it's the same result - no searches are done:

2017-10-07 13:15:20.2 - script started
--------------------------------------------------------------------------------

Live - ****@outlook.com

Live - ****@outlook.com

Points before:      3945
Points after:       3945
Points earned:         0
Lifetime Credits:   8595

--------------------------------------------------------------------------------
retry #2
Live - ****@outlook.com

Live - ****@outlook.com

Points before:      3945
Points after:       3945
Points earned:         0
Lifetime Credits:   8595

--------------------------------------------------------------------------------
retry #3
Live - ****@outlook.com

Live - ****@outlook.com

Points before:      3945
Points after:       3945
Points earned:         0
Lifetime Credits:   8595

--------------------------------------------------------------------------------
onComplete: account = Live_***@outlook.com, points = 0, retries = 3, totalPoints = 3945, lifeCredits = 8595, ifStatement = 'p ne 31'
onComplete: account = Live_***@outlook.com, points = 0, retries = 3, totalPoints = 3945, lifeCredits = 8595, ifStatement = 'P gt 475'
^C
Full log:
---------
onComplete: account = Live_***@outlook.com, points = 0, retries = 3, totalPoints = 3945, lifeCredits = 8595, ifStatement = 'p ne 31'
onComplete: account = Live_***@outlook.com, points = 0, retries = 3, totalPoints = 3945, lifeCredits = 8595, ifStatement = 'P gt 475'
onScriptFailure: -mail

I tried removing the events section, and redoing my entire config file from scratch, and neither seemed to alter anything.

I've also checked on the accounts manually, and they get points and can login just fine.

**Comment by kenneyhe** [comment]
tried #279?

**Comment by kenneyhe** [comment]
@fraser1974 a dupe? blank reward?

**Comment by fraser1974** [comment]
#280 another user recommended it.

**Comment by kenneyhe** [comment]
@fraser1974 does #284 fix it? please close if it does
