### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by SpongeCrafted** [sealemar/BingRewards#290]
Tried to run it, but got an Invalid Syntax.

C:\Users\Adm\Documents\Proj\BingRewards>python main.py
  File "main.py", line 64
    print "-" * 80
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by elisiano** [comment]
Wrong python version. 
You’re using python 3, the script require 2.7

**Comment by SpongeCrafted** [comment]
Oh I see, thanks. Are you thinking of supporting python 3 soon?

**Comment by elisiano** [comment]
it's not really up to me, I'm just a user 😃

**Comment by SpongeCrafted** [comment]
Oh that's awkward, sorry didn't read the username haha.

**Comment by amayer5125** [comment]
We don't plan to support python3 but we will more than likely support docker. This will make the version of python you have installed on your compouter irrelivent. You won't even need it installed.
