### ISSUE TITLE
import bingDashboardParser as bdp /  from bs4 import BeautifulSoup

### ISSUE THREAD

**Issue by FadeVT** [sealemar/BingRewards#294]
As of this morning, this is the message I am greeted with when running the script.  Any ideas?

```
Traceback (most recent call last):
  File "./main.py", line 28, in <module>
    import bingDashboardParser as bdp
  File "./pkg/bingDashboardParser.py", line 19, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

```

**Comment by someuserx** [comment]
BeautifySoup is now a requirement to run the script. [download the latest](https://www.crummy.com/software/BeautifulSoup/bs4/download/) and extract it to your pkg directory so it can find the bs4 folder.

**Comment by FadeVT** [comment]
Ah, that makes sence. Thanks!

**Comment by specu** [comment]
I think the bs4 directory from the bs tarball needs to go to where main.py is, not into pkg directory. it would be nice if the script checked if bs4 is present. right not it just gracefully exists without saying anything.
