### ISSUE TITLE
Searches not working - no errors

### ISSUE THREAD

**Issue by FadeVT** [sealemar/BingRewards#297]
Nov 1 - My new issue...

`fade@rpi:~/BingRewards$ ./main.py
2017-11-01 07:46:37.5 - script started
--------------------------------------------------------------------------------

For: Live - xxxxx@gmail.com

--------------------------------------------------------------------------------
/bin/sh: 1: /home/pi/BingRewards/notify/onScriptFailure.sh: not found`

**Comment by specu** [comment]
I'm running pre-beautifulsoup version and it runs fine.

**Comment by FadeVT** [comment]
I'm not sure I have a backup, but Ill look and see if I can find it. Thanks!

**Comment by bbmak** [comment]
is the new update required bs to run?

**Comment by specu** [comment]
@FadeVT that was bad advice i gave before. it looks like you just need to adjust your config xml to point to the correct location of onScriptFailure.sh (and presumably onScriptComplete.sh). your config currently points to /home/pi/BingRewards/notify/onScriptFailure.sh

**Comment by FadeVT** [comment]
Nah, that isn't an error that is hanging my script. I have never set up the onScriptFailure before. It always says that, then moves on to the next account. This one is different because it didn't say anything about the searches before that line and it didn't move to the next account after that line.

**Comment by specu** [comment]
there's a new problem that the script sometimes gets a blank page. you just have to try running again. Also I just posted a pull request, you may want to try that too.

**Comment by FadeVT** [comment]
I saw that. I figured they were related even before the pull request... That's why I marked this one as closed.  I haven't tried it yet to see if it works, but I am sure it will!  This seems to happen every single month. MS Likes to break stuff. 

Thanks for your help!

**Comment by FadeVT** [comment]
OK - So I just tried that, and got this... 

`fade@pi:~/BingRewards$ ./main.py
Traceback (most recent call last):
  File "./main.py", line 28, in <module>
    import bingDashboardParser as bdp
  File "./pkg/bingDashboardParser.py", line 228
    def createReward(reward, rUrl, rName, rPC, rPM, rDesc):
                                                                                           ^

`

**Comment by specu** [comment]
does it work if you edit bingDashboardParser.py and delete 2 instances of 
.encode('latin-1', 'ignore')
in there? (not the whole lines, just the test above)
