### ISSUE TITLE
Searches are not triggering rewards

### ISSUE THREAD

**Issue by ShoGinn** [sealemar/BingRewards#309]
The last 2 days the script has not worked to trigger the points.

Not sure how I can help to debug it, My account works when I log in and search "manually"

**Comment by specu** [comment]
try running it manually for 2 days

**Comment by ShoGinn** [comment]
No dice.. not working on 3 accounts.

**Comment by specu** [comment]
if you're running it on vps or a similar system then that might be it

**Comment by ShoGinn** [comment]
Yeah I’m running it on my Debian Docker box.

**Comment by LxanderUA** [comment]
I had the same problem 2 days ago.
Changing external IP or rebooting server solved problem.

**Comment by ShoGinn** [comment]
Changing the external IP is not an option, and rebooting is pointless since im running it as a container ;) 
Still no insight on whats going on even running verbose..

**Comment by ShoGinn** [comment]
I went the advanced route and forked a selenium build.. 
if anyone is interested, works mucho better ;)
https://github.com/ShoGinn/RewardsBot
