### ISSUE TITLE
Mobile searches not working at all...because of Edge Mobile Search Offer?

### ISSUE THREAD

**Issue by rustyshackleford2017** [sealemar/BingRewards#317]
This month they are allowing up to 200 points for using edge mobile. I downloaded the latest version of @baltimoron 's script and I noticed that the mobile searches did not run at all.

 I tried adding in the edge user agent but that didn't help. Is there a way to take advantage of the extra points offered or at least get mobile searches working again? I believe there bonus offer this month has some how changed the web code to where the bot algorithm does not function even for regular mobile searches.

**Comment by baltimoron** [comment]
Check out https://github.com/sealemar/BingRewards/issues/315

**Comment by rustyshackleford2017** [comment]
@baltimoron Oh thank you I didn't see that.

**Comment by specu** [comment]
@rustyshackleford2017 please dont forget to close this issue.

**Comment by rustyshackleford2017** [comment]
@specu oops sorry
