### ISSUE TITLE
Scripts are failing because of banner page change

### ISSUE THREAD

**Issue by akshyag** [sealemar/BingRewards#318]
Bing rewards banner page has been changed which will lead to failed script.
![banner](https://user-images.githubusercontent.com/29129879/35162866-88218f8c-fcf9-11e7-90e5-3c3c7945e803.png)

**Comment by baltimoron** [comment]
https://github.com/baltimoron/BingRewards fork works with the new dashboard. Hit rewards don't credit yet though, still working on that.

**Comment by specu** [comment]
@baltimoron I'm using your fork only for new dashboard, but I think it identifies the old dashboard and works with the old one as well - is that correct? does your for service hit rewards for old dashboard correctly? if so I dont see a reason it shouldnt be committed to the main repository, cc @amayer5125

**Comment by baltimoron** [comment]
@specu it will recognize either dashboard. The hit processing on the old dashboard isn't perfect, I think right now it only hits if the word "points" is in the button text (although I think currently it works the same on master). I know how to fix it to hit all rewards but never bothered implementing it once they started rolling out the new dashboard.
