### ISSUE TITLE
CRC check failed

### ISSUE THREAD

**Issue by specu** [sealemar/BingRewards#319]
what are those?
"onScriptFailure: CRC check failed 0xxxxxxxxx != 0xxxxxxxxxx"
last xxxxxxxxx 's vary

**Comment by baltimoron** [comment]
Is this a one off or does it keep happening?

**Comment by specu** [comment]
It happened 3 times today, all 3 times went through after retry. I saw it yesterday too.

**Comment by baltimoron** [comment]
I'm seeing something similar, will try to figure this out tomorrow.

**Comment by baltimoron** [comment]
@specu Latest commit added a catch for this error so it won't crash the script.

**Comment by specu** [comment]
Awesome - thank you. I'll report back if I see anything related to this tomorrow.
Your fork by now should be committed as a whole into the main tree by now. I think at this point most people run your fork because of the recent changes (cc @amayer5125  )

**Comment by baltimoron** [comment]
Yeah since it looks like most accounts are on the new dashboard now I can't imagine there are many people running the master branch. I'll put in a pull request later this week when I get around to cleaning up the files (mostly the tab/space issue)

**Comment by baltimoron** [comment]
Yeah some of my accounts are still on the old one. For accounts still on the old dashboard my fork runs the same way as the master branch (same code), the only modification is for the new dashboard.

**Comment by specu** [comment]
@baltimoron regarding tab, in the latest snapshot, "grep -R $'\t' *" only reports:
pkg/bingRewards.py:     #If we have already gone through the sign in process once, we don't need to do it again, just return the page
pkg/bingRewards.py:     if page.find('JavaScript required to sign in') == -1:
pkg/bingRewards.py:         return page
pkg/bingRewards.py:     # get form data
pkg/bingRewards.py:     return page
pkg/bingRewards.py:

**Comment by specu** [comment]
I got 1 crc today, but a retry works fine, so no biggie:
"IOError: CRC check failed "

**Comment by baltimoron** [comment]
Yeah it's not actually a fix, it just handles the error so that the script can retry instead of crashing.

**Comment by specu** [comment]
oh, in that case it works :)

**Comment by specu** [comment]
@baltimoron FYI catching IOError also addresses
"IOError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>"
so 2 for 1.
Previously 1 failure like that crashes entire script with multiple accounts. Now it's starting to look better and better.

**Comment by specu** [comment]
it would be great though if there verbose mode printed traceback into logs though. Right now it doesn't even show the line and script that caused failure. Preferably nice traceback from traceback module or at least line number and module where it was triggered.
