### ISSUE TITLE
Edge mobile rewards 200 per daystopped working

### ISSUE THREAD

**Issue by S3phi40T** [sealemar/BingRewards#320]
Hello,

I have an issue with Edge Mobile rewards.

I have changed SEARCH_MOBILE regex to "Edge mobile search" @ bingDashboardParser.py
Also changed UA Mobile to Mozilla/5.0 (Linux; Android 8.0; Pixel XL Build/OPP3.170518.006) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.145 Mobile Safari/537.36 EdgA/41.0.0.1273
It worked fine for some time. Searched for mobile records.
Manually works fine on Windows Chrome with User Agent switcher.
Any ideas?

**Comment by coollbv** [comment]
For me too
I've noticed after the last desktop search it gives
No Regex Match for this search error and then it pretty much doesn't go into mobile searches.

**Comment by godlessfather** [comment]
They've changed the description from "This month only, earn up to 200 points per day, 10 points per search on Microsoft Edge mobile app! Earn up to 100 points, 5 points per search, on any other mobile browser." to "This month only, earn 10 points per search on Microsoft Edge mobile app or 5 points per search on any other mobile browser, for up to 20 mobile searches per day." It throws off everything.

**Comment by LxanderUA** [comment]
As temporary solution I made this:
1. Made a copy scrypt directory
2. Changes in copy: pkg/bingDashboardParser.py string 
`SEARCH_AND_EARN_DESCR_RE = re.compile(r"[Uu]p to (\d+) points? (?:per day|today), (\d+) points? per search")`
to
`SEARCH_AND_EARN_DESCR_RE = re.compile(r"(\d+) points per search on any other mobile browser, for up to (\d+) mobile")`
3. Change in copy config.xml
`addSearchesMobile="20"`
4. Run this copy of scrypt after main scrypt.

That's spike-nail, if you understand what I mean, but it's worked, and I hope it's just temporary solution.

**Comment by baltimoron** [comment]
Latest commit on my fork should fix this.

**Comment by coollbv** [comment]
Works great as usual.
Thanks baltimoron!

**Comment by S3phi40T** [comment]
@baltimoron  Thank you!
Worked like a charm!

**Comment by specu** [comment]
@S3phi40T please dont forget to close this issue.
