### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by specu** [sealemar/BingRewards#323]
I think one of the activities is causing the script to fail with 502 as of today.

**Comment by ndbills** [comment]
I am getting the same errors as well, but haven't had time to dig into it today.

**Comment by rustyshackleford2017** [comment]
@specu I am also getting the 502 on all my accounts.

**Comment by baltimoron** [comment]
Seeing this when I log in manually and try to hit a link from the flyout page. I think it's an internal issue on the MS side.

**Comment by specu** [comment]
@baltimoron looks normally when i log in with browser. 
in getDashboardPage() after 'JavaScript required to sign' in the form contains new parameter pprid, i tried adding it to the form but did not help. error 502 is returned after submitting that form.
minor note, there's a bunch of tabs in that file, kind of threw off my editor, probably something normal to deal with for more advanced python people.

**Comment by baltimoron** [comment]
@specu yeah I'm seeing that too. Also tried adding it but I'm still getting the same result. The weird thing is that when I login manually my first click always returns the 502 error as well, that's why I was thinking there might be an issue on their end. I'm also seeing this issue reported elsewhere by people who aren't using a bot.

**Comment by baltimoron** [comment]
also that tab/space thing is super annoying, I thought I had converted them all to spaces but I guess not. Which editor are you using?

**Comment by specu** [comment]
@baltimoron I'm using ultraedit.

**Comment by S3phi40T** [comment]
Same here - 502 error.

**Comment by LxanderUA** [comment]
I think Microsoft fixed something. Script working ok.

**Comment by specu** [comment]
closing
