### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by pavanpalaksha** [sealemar/BingRewards#328]
Not sure if I am the only one seeing this. I also see that bing has changed their dashboard layout. 

2018-01-25 14:24:04.7 - script started
--------------------------------------------------------------------------------
For: Live - xxx@gmail.com

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 278, in <module>
    __run(config)
  File "main.py", line 205, in __run
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "main.py", line 167, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "main.py", line 55, in earnRewards
    rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "pkg/bingDashboardParser.py", line 114, in parseDashboardPage
    for ddiv in rewardsDashboard.find_all('div', class_='spacer-32-top display-table'):
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by specu** [comment]
your account got converted to the new dashboard
checkout #303 and please close this if 303 works for you.

**Comment by puternutt** [comment]
@specu have you got the script working? I did a git on the new files from sealemar today after receiving the attributeError: 'NoneType' object has no attribute 'find_all' error in the bingDashboardParser.py line 114.  I have some if not all of the accounts converted to the new dashboard. I tried Baltimoron's version, but getting an i/o error on it. I posted the error on #303 

You all have been pretty active on here lately with the MS updates. I just want to say I appreciate everyone's work on this and hope it continues.

**Comment by specu** [comment]
@puternutt IOError is fine, just try again, it happens often, but it's caught and retried. This is related to the fact that MS compresses pages and for some reason decompression doesnt always work.
Yes sealemar is way behind, Baltimoron should be a dev here.

**Comment by pavanpalaksha** [comment]
#303 did resolved the issue. thanks @specu
