### ISSUE TITLE
baltimoron'S latest commit 5288c2 is broken - syntax error

### ISSUE THREAD

**Issue by S3phi40T** [sealemar/BingRewards#332]
@baltimoron 
commit 5288c2e68dc7cfbafefc8b60622a7562e0d42304

Traceback (most recent call last):
  File "/home/pi/rewards/main.py", line 24, in <module>
    from bingRewards import BingRewards
  File "/home/pi/rewards/pkg/bingRewards.py", line 18, in <module>
    import bingDashboardParser as bdp
  File "/home/pi/rewards/pkg/bingDashboardParser.py", line 248
    except
          ^
SyntaxError: invalid syntax

**Comment by specu** [comment]
@baltimoron I thought so too, but it's not just that :)
-                except
-                    ValueError: pass
+                except ValueError:
+                    pass

**Comment by S3phi40T** [comment]
@baltimoron download one file and whole commit, error is still there.

Traceback (most recent call last):
  File "/home/pi/rewards/main.py", line 24, in <module>
    from bingRewards import BingRewards
  File "/home/pi/rewards/pkg/bingRewards.py", line 18, in <module>
    import bingDashboardParser as bdp
  File "/home/pi/rewards/pkg/bingDashboardParser.py", line 249
    ValueError: pass
              ^
SyntaxError: invalid syntax

**Comment by S3phi40T** [comment]
@specu I have tried your solution.
It works as long as it's replaced exactly as you posted. 

First I replaces spaces with tabs and it wasn't working ;)

...so for the others, use spaces, not tabs., whatever editor you use.

**Comment by S3phi40T** [comment]
@baltimoron I'm not sure if it's new dashboards' issue, but script exits completely after first account won't collect any points. 

I miss your CRC checks and ability to continue after error ;)

2018-01-31 - script started
--------------------------------------------------------------------------------

Live - xxx@xxx.com
Result 1/17:
-----------
name        : Shop & earn
url         : https://www.bing.com/explore/rewards-shop-and-earn?FORM=ML13VU&CRE                                                                                                                                                             A=ML13VU&wt.mc_id=ML13VU&rnoreward=1
progressCur : 0
progressMax : 20000
progress %  : 0.00%
description : Earn 1 point per $1 spent at the Microsoft Store. Terms apply.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 2/17:
-----------
name        : Keep them reading
url         : https://www.microsoft.com/en-us/store/new/books/pc?target=books,,9                                                                                                                                                             41&OCID=CatPromoBooks-Jan-18-en-us-dash-1
progressCur : 0
progressMax : 10
progress %  : 0.00%
description : Find great books for young readers, from children's to young adult                                                                                                                                                              titles.
   Error    :   true
   Message  : Expected to earn 10 points, but earned 0 points. Check error_20180                                                                                                                                                             131-130603.164004.html for further information
   Action   : hit


Live - xxx@xxx.com

Points before:      12345
Points after:       12345
Points earned:         0
Lifetime Credits:   123456

--------------------------------------------------------------------------------
retry #2
Live - xxx@xxx.com
Result 1/17:
-----------
name        : Shop & earn
url         : https://www.bing.com/explore/rewards-shop-and-earn?FORM=ML13VU&CREA=ML13VU&wt.mc_id=ML13VU&rnoreward=1
progressCur : 0
progressMax : 20000
progress %  : 0.00%
description : Earn 1 point per $1 spent at the Microsoft Store. Terms apply.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

Result 2/17:
-----------
name        : Keep them reading
url         : https://www.microsoft.com/en-us/store/new/books/pc?target=books,,941&OCID=CatPromoBooks-Jan-18-en-us-dash-1
progressCur : 0
progressMax : 10
progress %  : 0.00%
description : Find great books for young readers, from children's to young adult titles.
   Error    :   true
   Message  : Expected to earn 10 points, but earned 0 points. Check error_20180131-130655.479954.html for further information
   Action   : hit


Live - xxx@xxx.com

Points before:      12345
Points after:       12345
Points earned:         0
Lifetime Credits:   123456

--------------------------------------------------------------------------------
retry #3

For: Live - xxx@xxx.com

--------------------------------------------------------------------------------

Full log:
---------
Empty log
onScriptFailure: -mail

**Comment by baltimoron** [comment]
@specu thanks. Must be too early for me.

**Comment by z0oinks** [comment]
Getting the same issue. Second account won't run and getting

Empty log
onScriptFailure: -mail

First account works fine

**Comment by specu** [comment]
before reporting always please do `git pull` to make sure you're running the latest version. I think that will fix it.

**Comment by z0oinks** [comment]
<git pull> says it's up to date

**Comment by specu** [comment]
@z0oinks please dont forget to close if this is solved.

**Comment by z0oinks** [comment]
@specu It's not, my second account doesn't work still

**Comment by specu** [comment]
@z0oinks  you are running the latest version of bingrewards and you still get "invalid syntax"?

**Comment by z0oinks** [comment]
@specu Actually I get a separate error, I'll make a separate issue about it
