### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by coollbv** [sealemar/BingRewards#333]
So on a couple of the accounts I see this after the script is executed...

--------------------------------------------------------------------------------

For: Live - xxxxxx@gmail.com

--------------------------------------------------------------------------------
The system cannot find the path specified.

And it kicks it out.

I tried commenting out events in config.xml. Didn't help.

**Comment by coollbv** [comment]
It seems something changed overnight again since now the script gives "The system cannot find the path specified" after finishing searches and not being able to display points earned etc.

**Comment by specu** [comment]
@coollbv you're probably running on windows and dont have the on error script set up correctly.

**Comment by coollbv** [comment]
Yes, I am on Windows. However, it was working fine till today. Haven't changed anything in config...

**Comment by specu** [comment]
yes, but I think it's trying to report an error and it can't find the script to do error. Please make sure onScriptFailure and onScriptComplete sections in config can be executed without error

**Comment by coollbv** [comment]
It had to do with the 400 error that @baltimoron fixed...

**Comment by specu** [comment]
yes, but it should show the error not "The system cannot find the path specified" if you had it set up correctly.
