### ISSUE TITLE
Mobile points - change back

### ISSUE THREAD

**Issue by LxanderUA** [sealemar/BingRewards#335]
Change back bingDashboardParser.py, line 57
`SEARCH_MOBILE        = (3,    "Mobile search",                     None, False, Action.SEARCH)`

and I propose to change main.py, line 59 to
`print ("%s - %s - %6d" % (reportItem.accountType, reportItem.accountLogin,  reportItem.oldPoints))`
You can see, how many point you have, if script fall down due to searches.

And have someone any issues, why daily quizz and clicks doesn't work by script? Or it mustn't working?

**Comment by specu** [comment]
this change is committed. pls close
