### ISSUE TITLE
Not Running Mobile Searches

### ISSUE THREAD

**Issue by z0oinks** [sealemar/BingRewards#337]
Is there anything special I need to do to enable mobile searches?

Also, how do I get the Edge search bonus?

**Comment by specu** [comment]
Edge search bonus is done and mobile searches should be enable by default. there's was a change this morning so if you do `git pull` they'll work again. (please close if solved)

**Comment by z0oinks** [comment]
What do you mean Edge bonus is done? I'm still showing an extra 20 points per day for using it.
Would adding <ua_mobile>![CDATA[Mozilla/5.0 (Linux; Android 8.0; Pixel XL Build/OPP3.170518.006) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.145 Mobile Safari/537.36 EdgA/41.0.0.1273]]</ua_mobile> get me those extra points?

And thanks, that made mobile searches work

**Comment by specu** [comment]
20 extra are for edge desktop browser, it was suggested that the easiest way to go is to add to config:
        addSearchesDesktopSalt="4"
edge mobile 2x bonus is done as of this morning so your mobile string wont get you extra points, but i think it's smart to keep it in there (MS will obviously prefer its technologies in rewards).

**Comment by z0oinks** [comment]
All the way at the top? It was set to 20, so just change it to 4?

**Comment by specu** [comment]
20 is good. is your desktop string set to edge?
<ua_desktop>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063</ua_desktop>

**Comment by z0oinks** [comment]
Added it now, thanks for the help!
