### ISSUE TITLE
IOError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by specu** [sealemar/BingRewards#340]
started this morning.

**Comment by baltimoron** [comment]
Looking at this now, do you know exactly where it's happening?

**Comment by baltimoron** [comment]
Looks like somehow a space is getting inserted into the crepe reward and that's causing the crash.

**Comment by baltimoron** [comment]
Try the latest commit, it should work now.

**Comment by specu** [comment]
confirming this works. Could you please do pull request for this? I can put it in if you dont have the time.
