### ISSUE TITLE
Script doesn't work for level 1 account

### ISSUE THREAD

**Issue by AMTNate** [sealemar/BingRewards#341]
I just created a second account to run along side my main account, and I noticed that even though I had everything set up properly, the script won't actually work until the account is at level 2.

**Comment by specu** [comment]
you have to get to level 2 manually. should be 1 day. the script doesnt support level 1 currently.

**Comment by S3phi40T** [comment]
@AMTNate 
It always supported Level 2 and US region only.

**Comment by AMTNate** [comment]
That makes sense. The first account I started with was already level 2, so I never had a problem. Maybe this could be put in the documentation somewhere?
