### ISSUE TITLE
Unknown URL Type

### ISSUE THREAD

**Issue by z0oinks** [sealemar/BingRewards#349]
Whenever I try to run my second account, I get the error:
ValueError: unknown url type: /news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1

**Comment by specu** [comment]
what does `git log -1 --no-color` say?

**Comment by z0oinks** [comment]
commit a614d2ceb69bc1980ab48ebbdc8eb8e443d89fd1 (HEAD -> master, origin/master, origin/HEAD)
Merge: 02a3730 e567940
Author: Alex Mayer <amayer5125@gmail.com>
Date:   Mon Feb 5 21:23:14 2018 -0500

    Merge pull request #342 from baltimoron/master

    Fixes for spaces in url, substring error, and mobile search regex

**Comment by aliasfoxkde** [comment]
As far as I can tell, this error occurs when an account is Level 1.

**Comment by soccerob** [comment]
I can confirm that I'm getting this error and that my account is level 1. Will try again once I get up to level 2. I'm jumping back in after a long absence.

**Comment by z0oinks** [comment]
Looks like it started working after getting to level 2. Closed!
