### ISSUE TITLE
ValueError: 'points.' is not in list

### ISSUE THREAD

**Issue by Dreded** [sealemar/BingRewards#352]
Hey guys great work.. unfortunately it does not work for me :(

Here is the entire output:

PS E:\git\BingRewards> python2 .\main.py
2018-02-12 12:49:29.9 - script started
--------------------------------------------------------------------------------

ValueError: 'points.' is not in list

For: Live - xxxx@hotmail.com

--------------------------------------------------------------------------------
retry #2
ValueError: 'points.' is not in list

For: Live - xxxx@hotmail.com

--------------------------------------------------------------------------------
retry #3
ValueError: 'points.' is not in list

For: Live - xxxx@hotmail.com

--------------------------------------------------------------------------------
onError: account = Live_xxxx@hotmail.com, points = 0, retries = 3, totalPoints = 0, lifeCredits = 0, ifStatement = 'None', error = ''points.' is not in list'
Total points earned: 0

2018-02-12 12:50:26.9 - script ended

Full log:
---------
onError: account = Live_xxxx@hotmail.com, points = 0, retries = 3, totalPoints = 0, lifeCredits = 0, ifStatement = 'None', error = ''points.' is not in list'

**Comment by godlessfather** [comment]
Are you running that from outside of the US by chance?

**Comment by Dreded** [comment]
I am indeed in Canada

**Comment by godlessfather** [comment]
See #344. It may be addressed at some point, but the script doesn't work outside of the US.

**Comment by aliasfoxkde** [comment]
@Dreded That's against the Bing Rewards Terms of Use: "The Program is open to users who reside in the fifty (50) United States or the District of Columbia and who are at least thirteen (13) years of age and is void where prohibited by law." - https://www.bing.com/rewards/tou

To get around it you have to use a proxy or VPN but it's outside the scope of the bot itself and is a little more technical.

**Comment by godlessfather** [comment]
@aliasfoxkde It's no longer called Bing Rewards. Microsoft Rewards is indeed [open to residents of Canada](https://rewards.microsoft.com/ms-rewards-announcement?mkt=en-ca).

**Comment by specu** [comment]
@godlessfather if you're submitting updates to docs, could you please mention in there that it doesnt support Level 1?

**Comment by godlessfather** [comment]
@specu Done. Thanks for the reminder.

**Comment by S3phi40T** [comment]
@aliasfoxkde 
Microsoft Rewards is currently only available in the US, GB, FR, DE, CA and AU.
It's not only US anymore for long time.
Every region has own daily activities, own points set, names, etc.. 

@Dreded script is unfortunately adapted only to US region. Period. Tried to use it for other regions. Failed.
Already commented it @ https://github.com/sealemar/BingRewards/issues/344

**Comment by aliasfoxkde** [comment]
@godlessfather thanks. I was following the older "Terms of Use" which are much longer, and some of them still appear to apply though not in the new terms.

**Comment by Dreded** [comment]
fixed it... all I had to do was remove the 'period' from the end of 'points.' on line #196 of bingDashboardParser.py I will do a few days of testing and then submit a code fix for Canada

**Comment by Dreded** [comment]
made the change here... https://github.com/Dreded/BingRewards

**Comment by godlessfather** [comment]
@Dreded I can confirm that it works on my Canadian friend's account. I'll post back for tomorrow to test a second time.

**Comment by Dreded** [comment]
made a pull request that fixes the issue.. #356
