### ISSUE TITLE
Breaks if reward URL is relative

### ISSUE THREAD

**Issue by I-Dont-Remember** [sealemar/BingRewards#366]
Been digging through the code to see if I missed something obvious, but so far it seems like an actual bug.  Upon running this script with my account, both in Docker and from my own PC i end up getting the same error:
```
ValueError: unknown url type: /news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1

For: Live - my-name@gmail.com
```

Using verbose we can see the offending reward:
```
Reward 2/10:
-----------
name        : Daily search
url         : /news?q=us+news&FORM=ML11Z9&CREA=ML11Z9&wt.mc_id=ML11Z9&rnoreward=1&rnoreward=1
progressCur : 0
progressMax : 50
progress %  : 0.00%
description : Earn up to 50 points per day, 5 points per search.
hit identifier: ENUS_search_level1_APR18_HOLDOUT
hit hash: 6d30b30f8689391454213d1565902932490d63b7573efefa3d895795d003dada
```
I only had a little time to look into it, but I got to seeing it failing in the `bingRewards.process`, with urllib2 failing in getting the page because it doesn't have a full path.  I can try and help dig into this eventually once things get less crazy if someone doesn't jump on it before then.

**Comment by specu** [comment]
the script doesnt support Level 1 at this point. You typically can get to level 2 within an hour after sigining up so it doesnt make sense to work on that functionality.

**Comment by I-Dont-Remember** [comment]
Ah makes sense, I forgot it had been long enough I dropped back down.  Thanks for the assistance!

**Comment by specu** [comment]
Please consider closing this. I think level 1 support request is there already but I'd say it's low priority.
