### ISSUE TITLE
Issue with getRewardsPoints?

### ISSUE THREAD

**Issue by duddles** [sealemar/BingRewards#370]
Today it wasn't running - it sees like the url that getRewardsPoints() calls isn't working.

url is "www.bing.com/rewardsapp/reportActivity"

I just changed getRewardsPoints to return 100 to get it to run

Not sure if maybe the url is just down temporarily

**Comment by patrickbryan** [comment]
Same issue for me. I made a similar change to get things working.

**Comment by Yoduh** [comment]
I made the change, and the script runs, but I'm not getting any points on my account.

**Comment by matchqq** [comment]
How to make the change to get it to work?

**Comment by DimaRazb** [comment]
valueError: substring not found
for me today.

**Comment by LYHTSPD** [comment]
I am getting the same error DimaRazb

**Comment by dronenb** [comment]
Check my repo that I forked.  It should work.  I submitted a pull request also.

**Comment by specu** [comment]
I only changed 2 instances of
t.innerHTML='
to
var b='
in pkg/bingRewards.py
and I think that should do it. I'm testing it now.

**Comment by dronenb** [comment]
@akshyag submitted a pull request the solution you're suggesting... I reinvented the wheel due to the fact that I thought the reportActivity page was no longer displaying points, but I guess I overlooked it.... You should totally use his repo until it gets merged.

**Comment by specu** [comment]
I submitted my least invasive patch for consideration, but it's awesome to see that many contributors

**Comment by DimaRazb** [comment]
@specu thanks dude, these two lines did the trick!

**Comment by adambird79** [comment]
I did the bingRewards.py which works for mobile searches but not PC searches

**Comment by dronenb** [comment]
@adambird79 Looks like you're having the same issue as @Yoduh, but I'm fairly sure that issue is unrelated to the getRewardsPoints issue, as this issue only has to do with the way the script calculates how many points you earned, not how it actually earns the points.. You might want to open a new issue, but I would wait until after the pull request for the getRewardsPoints issue gets merged.

**Comment by dronenb** [comment]
@adambird79 It appears as though Microsoft's counter might be broken, which has nothing to do with our code.  See: https://www.reddit.com/r/MicrosoftRewards/comments/8nqmax/not_earning_search_points_today/

**Comment by amayer5125** [comment]
This issue should be fixed with #373
