### ISSUE TITLE
Microsoft Launcher browser string?

### ISSUE THREAD

**Issue by specu** [sealemar/BingRewards#375]
sort of PSA: rewards.microsoft.com/explore/ms-launcher-offer (not hyperlinked to avoid referrer back to here).
if anyone figures out browser string or how to get that, please share

**Comment by specu** [comment]
"In order to be eligible for the double mobile search points offer during the promotional period (05/31/2018 through 06/30/2018) Microsoft Rewards members must: Install the Microsoft Launcher app on your Android device; from your default browser, sign in to Bing with the Microsoft account associated with Microsoft Rewards; search Bing using the Microsoft Launcher search bar. "

**Comment by powder012** [comment]
The only noticeable difference I see is EdgA/42.0.0.2033  But I haven't checked/updated my useragent strings in quite awhile.

I suspect since you have to 'sign in' to the Launcher your account tracks somehow that way.

**Comment by specu** [comment]
promo is over. closing.
