### ISSUE TITLE
 Message  : Didn't earn any points for click

### ISSUE THREAD

**Issue by lukedukeus** [sealemar/BingRewards#380]
I keep getting a message output like this:

Result 2/24:
-----------
name        : Claim your points
url         : https://account.microsoft.com/rewards
progressCur : 0
progressMax : 100
progress %  : 0.00%
description : You've set a goal! Here's 100 bonus points to help you get there.
hit identifier: 10XMSRewards_a30081647
hit hash: 5742544dc029170371c1ebf0f39f0580c48b41be22aaf1b718b6f0c6dd857d54
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn
-------------

why is it not receiving these points? how can I fix this?
I know this is in issue 227 and 300 but i havent found the solution

**Comment by specu** [comment]
you need to get to Level 2 manually.
Please close if this helped.

**Comment by coollbv** [comment]
Yeah, the 100 bonus points have to be claimed manually.
