### ISSUE TITLE
IOError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by duddles** [sealemar/BingRewards#384]
It's been working well for me - but today it will only do 1 or 2 searches before saying:
IOError: HTTP Error 400: Bad Request

Curious if this is something anyone else is seeing as well, or what I might look into for fixing it.

**Comment by LYHTSPD** [comment]
I am seeing this as well across multiple accounts starting this morning.

**Comment by z0oinks** [comment]
Happens to me across 3 accounts

**Comment by cmdrshepard84** [comment]
Same here, 3 accounts, maybe 1 or 2 searches and it craps out.

**Comment by duddles** [comment]
It seems to be happening when it follows a link
