### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by coollbv** [sealemar/BingRewards#395]
Last 2 days new error keeps popping up
ValueError: unknown url type: ms-rewards

I'm using 3.16.7 from @dwait

**Comment by specu** [comment]
3.16.7 is the current production version of the script.  
have you seen this?
https://github.com/sealemar/BingRewards/pull/393  
I'll try to fix ms-rewards today but that's an error that doesnt prevent the script from running, it just shows error in the end. You could run it a second time to be sure.

**Comment by coollbv** [comment]
I have seen it but I opted to wait for the quiz spot for a bit just to see if there are any issues.
Yeah the script keeps running. The issue only happens after all the mobile searches are done. What it does it does 4 retries (that's how many I put in the config) and it doesn't log the points so that's where it's messing me up.

**Comment by specu** [comment]
3 people have tested and no issues. I'm on 30+ day streak myself on all accounts.
I'd like to see it accepted so I can submit more patches off of that.

**Comment by specu** [comment]
@coollbv please try this if that works for you:
https://github.com/sealemar/BingRewards/pull/396

you could try apply it via:
wget https://github.com/sealemar/BingRewards/pull/396.patch
patch -p1 < 396.patch

**Comment by coollbv** [comment]
Worked like a charm!
