### ISSUE TITLE
Correct syntax for Bing rewards?

### ISSUE THREAD

**Issue by deadman36g** [sealemar/BingRewards#402]
I have not been able to successfully get the Bing Rewards.

The syntax I am using is
 `<ua_mobile><![CDATA[Mozilla/5.0 (Linux; Android 8.0; Pixel XL Build/OPP3.170518.006) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.145 Mobile Safari/537.36 EdgA/41.0.0.1273]]></ua_mobile>`

I am just curious if this is correct or not?

**Comment by specu** [comment]
This works:  
<ua_mobile>Mozilla/5.0 (Linux; Android 7.0; HTC 10 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.145 Mobile Safari/537.36 EdgA/41.0.0.1138</ua_mobile>  
You dont need CDATA part

**Comment by deadman36g** [comment]
Thanks @specu that worked a charm
