### ISSUE TITLE
Displaying Account Information Differently

### ISSUE THREAD

**Issue by xwsxethan** [sealemar/BingRewards#59]
So this isn't an issue really so much as a feature request. It would be nice in some cases to be able to see the email account first before running the searches, rather than having to wait until the end to see it. I realize some people may have a preference for the other way, so could you possibly add a new config for users to set a flag for display account info before, after, or both maybe? You'd still want the summary of points before, after, gained, etc. at the end still, but just print out the email account upfront.

This is nothing crucial obviously and if it would take too much work, then don't worry about it. Just a friendly thought I figured I would pass along. I may look into it myself if time permits. Love the system and all the hard work by the way. Thank you so much!

**Comment by amayer5125** [comment]
@xwsxethan @sealemar should we close this issue since we merged code to add the feature?

**Comment by sealemar** [comment]
sure, thanks for working on that.
