### ISSUE TITLE
Random shutdown during script (rsyslogd)

### ISSUE THREAD

**Issue by Dmurph24** [sealemar/BingRewards#99]
Most of the time, main.py works completely fine and without errors, but I have noticed a couple times that something goes wrong in the script and causes a shutdown. Before I posted this as an issue I tested it on another device to ensure it wasnt my machine and sure enough it did the same time after a couple runs. Heres some details...

In the log I get an error similar to this
<code>rsyslogd: [origin software="rsyslogd" swVersion="5.8.11" x-pid="1616" x-info="http://www.rsyslog.com"] rsyslogd was HUPed</code>
After some research I found out that this is an unexpected shutdown

I also found out that this most likely occurs when the program has already ran through a couple of accounts and has been running for a little bit. Never has the error occurred on a event handler. It must be when starting a new account or ending an account. 

Do you have any ideas why this is occurring? It is happening once for every three days and I have to manually run it those days when it crashes.

**Comment by Dmurph24** [comment]
This issue was most likely not caused by the program so you can go ahead and mark this as resolved. 

Also, I'd like to note that I built an extension off of your repo to support database interaction and improved emailing. There are quite a few differences so I don't think it would be appropriate to merge these changes. I made a repo here: https://github.com/Dmurph24/bing-bot/

**Comment by sealemar** [comment]
Email representation looks nice. Can be merged if you submit a pull request. There should be no change to the Python code, html representation only. Also it doesn't matter which cmd line email client you're using, thus don't hesitate to submit a pull request.

Closing the issue for the mean time.

**Comment by Dmurph24** [comment]
There are quite a few code changes as the script now runs off a database that the user configures. For example, main.py connects to the database and looks for all the accounts to run instead of the config file. All points are stored in the DB. This allows for multiple machines to have the script on it to communicate.

If you still think a pull request would be helpful please let me know, but there are a lot of changes, take a look at main.py on my repo if you want.

**Comment by sealemar** [comment]
That was likely to be a misunderstanding. Possibly I wasn't clear enough. I was saying about the email representation only. Shifting the configuration from a file to a database may seem as an interesting step to take. Considering how few of accounts a usual user may have and also taking into account that accounts traversal has to be sequential, the database looks like an expensive overhead.

The original script is self sufficient and will not run any searches if the number of reward searches has already been expired making the point of cross host communication not that much significant. You may also imagine how Bing! would react on an unusual activity of two hosts accessing the same account at the same time. Therefore I can hardly imagine how multiple hosts can help. With a little change one host can run all 100 searches per account all at once, however Bing! will definitely punish such a negligence.

Hope all of that makes sense. I will be happy to review a pull request for the email representation, though.

**Comment by Dmurph24** [comment]
I don't think you understand. The multiple hosts is so you can run many accounts NOT at the same time. You may only have 5 account per external IP address otherwise they will get banned. So by using multiple hosts you may have more than 5 accounts for one IP. In other words, if you use your current program with 6 accounts, they will all be banned extremely fast.

**Comment by sealemar** [comment]
good. Anyway, if you want to have your email template get merged, feel free to submit it.
